# flake8: noqa: F401,F811,E501
"""Vision module for CAD ML Platform.

Provides vision-based analysis of engineering drawings with OCR integration.

Supported providers:
- stub: Testing stub (no API key required)
- deepseek: DeepSeek VL API
- openai: OpenAI GPT-4o/GPT-4-Vision
- anthropic: Claude 3 family (Opus, Sonnet, Haiku)
"""

from .base import (
    OcrResult,
    VisionAnalyzeRequest,
    VisionAnalyzeResponse,
    VisionDescription,
    VisionError,
    VisionInputError,
    VisionProvider,
    VisionProviderError,
)
from .manager import VisionManager
from .providers import (
    # Stub provider
    DeepSeekStubProvider,
    create_stub_provider,
    # DeepSeek provider
    DeepSeekVisionProvider,
    create_deepseek_provider,
    # OpenAI provider
    OpenAIVisionProvider,
    create_openai_provider,
    # Anthropic provider
    AnthropicVisionProvider,
    create_anthropic_provider,
)
from .factory import (
    create_vision_provider,
    get_vision_provider,
    get_available_providers,
)
from .resilience import (
    ResilientVisionProvider,
    RetryConfig,
    CircuitBreakerConfig,
    CircuitState,
    CircuitOpenError,
    ProviderMetrics,
    create_resilient_provider,
)
from .cache import (
    VisionCache,
    CachedVisionProvider,
    CacheStats,
    create_cached_provider,
)
from .rate_limiter import (
    RateLimitConfig,
    RateLimitStats,
    RateLimitError,
    RateLimitedVisionProvider,
    TokenBucketRateLimiter,
    create_rate_limited_provider,
)
from .batch import (
    BatchProcessor,
    BatchResult,
    BatchProgress,
    process_images_batch,
)
from .comparison import (
    ProviderComparator,
    ComparisonResult,
    SelectionStrategy,
    compare_providers,
)
from .streaming import (
    StreamingVisionProvider,
    StreamEvent,
    StreamEventType,
    StreamConfig,
    BatchStreamProcessor,
    stream_analysis,
    generate_sse_stream,
    create_streaming_provider,
)
from .prompts import (
    PromptManager,
    PromptTemplate,
    PromptConfig,
    PromptType,
    get_prompt_manager,
    get_prompts,
    register_custom_template,
    BUILTIN_TEMPLATES,
)
from .cost_tracker import (
    CostTracker,
    CostTrackedVisionProvider,
    PricingTier,
    UsageRecord,
    UsageSummary,
    BudgetConfig,
    get_cost_tracker,
    create_cost_tracked_provider,
)
from .webhooks import (
    WebhookManager,
    WebhookVisionProvider,
    WebhookConfig,
    WebhookEvent,
    WebhookEventType,
    WebhookStatus,
    DeliveryResult,
    get_webhook_manager,
    create_webhook_provider,
)
from .persistence import (
    ResultPersistence,
    PersistentVisionProvider,
    StorageProvider,
    InMemoryStorage,
    StorageBackend,
    AnalysisRecord,
    QueryFilter,
    QueryResult,
    get_persistence,
    create_persistent_provider,
)
from .analytics import (
    VisionAnalytics,
    ProviderStats,
    TimeBucket,
    TrendData,
    TimeGranularity,
    AnalyticsReport,
    create_analytics,
)
from .failover import (
    FailoverManager,
    FailoverVisionProvider,
    ProviderEndpoint,
    ProviderHealth,
    FailoverStrategy,
    FailoverConfig,
    FailoverResult,
    create_failover_provider,
)
from .health import (
    HealthMonitor,
    HealthAwareVisionProvider,
    HealthMetrics,
    HealthStatus,
    HealthAlert,
    AlertSeverity,
    HealthCheckConfig,
    HealthDashboard,
    get_health_monitor,
    create_health_aware_provider,
)
from .preprocessing import (
    ImagePreprocessor,
    ImageValidator,
    PreprocessingVisionProvider,
    PreprocessingConfig,
    ImageFormat,
    ImageInfo,
    ValidationResult,
    create_preprocessing_provider,
)
from .load_balancer import (
    LoadBalancer,
    LoadBalancedVisionProvider,
    LoadBalancingAlgorithm,
    LoadBalancerConfig,
    LoadBalancerStats,
    ProviderNode,
    create_load_balanced_provider,
)
from .logging_middleware import (
    LoggingMiddleware,
    LoggingVisionProvider,
    LoggingConfig,
    LogLevel,
    LogDestination,
    RequestLog,
    ResponseLog,
    PerformanceMetrics,
    LogHandler,
    ConsoleLogHandler,
    FileLogHandler,
    JSONLogHandler,
    CallbackLogHandler,
    get_logging_middleware,
    create_logging_provider,
)
from .profiles import (
    ProfileManager,
    ProfileConfig,
    ProviderConfig,
    ProfileType,
    ProviderType,
    RetryConfig as ProfileRetryConfig,
    RateLimitConfig as ProfileRateLimitConfig,
    CacheConfig as ProfileCacheConfig,
    CircuitBreakerConfig as ProfileCircuitBreakerConfig,
    TimeoutConfig,
    ProfileEnvironmentLoader,
    get_profile_manager,
    get_profile,
    create_profile,
)
from .tracing import (
    Tracer,
    TracingVisionProvider,
    Span,
    SpanStatus,
    SpanKind,
    RequestContext,
    SpanExporter,
    ConsoleSpanExporter,
    TracerConfig,
    get_current_context,
    set_current_context,
    get_tracer,
    create_tracing_provider,
)
from .metrics_exporter import (
    MetricsExporter,
    MetricsVisionProvider,
    MetricType,
    MetricValue,
    HistogramValue,
    MetricBackend,
    InMemoryMetricBackend,
    CallbackMetricBackend,
    MetricsConfig,
    get_metrics_exporter,
    create_metrics_provider,
)
from .embedding import (
    ImageEmbedder,
    SimilarityIndex,
    SimilarityVisionProvider,
    HashAlgorithm,
    ImageHash,
    EmbeddingVector,
    ImageRecord,
    SimilarityResult,
    CryptographicHashGenerator,
    PerceptualHashGenerator,
    create_similarity_provider,
)
from .quotas import (
    QuotaManager,
    Throttler,
    QuotaVisionProvider,
    QuotaPeriod,
    ThrottleStrategy,
    QuotaAction,
    QuotaLimit,
    QuotaUsage,
    ThrottleConfig,
    ThrottleState,
    QuotaCheckResult,
    ProviderQuotaConfig,
    QUOTA_PRESETS,
    THROTTLE_PRESETS,
    get_quota_preset,
    get_throttle_preset,
    create_quota_provider,
)
from .ab_testing import (
    ExperimentManager,
    ABTestingVisionProvider,
    ExperimentConfig,
    ExperimentStatus,
    ExperimentResult,
    ExperimentAnalysis,
    Variant,
    VariantType,
    VariantStats,
    AllocationStrategy,
    StatisticalMethod,
    get_experiment_manager,
    create_ab_testing_provider,
)
from .validation import (
    ResponseValidator,
    ValidatingVisionProvider,
    ValidationSchema,
    ValidationRule,
    ValidationResult,
    ValidationIssue,
    ValidationSeverity,
    ValidationRuleType,
    ValidationStats,
    ValidationError,
    STANDARD_SCHEMA,
    STRICT_SCHEMA,
    OCR_SCHEMA,
    create_validating_provider,
)
from .audit import (
    AuditLogger,
    AuditingVisionProvider,
    AuditEntry,
    AuditContext,
    AuditConfig,
    AuditEventType,
    AuditLevel,
    AuditStorage,
    InMemoryAuditStorage,
    RetentionPolicy,
    get_audit_logger,
    create_auditing_provider,
)
from .multiregion import (
    RegionRouter,
    MultiRegionVisionProvider,
    Region,
    RegionConfig,
    RegionHealth,
    RegionStatus,
    RoutingStrategy,
    RoutingDecision,
    LatencyMeasurer,
    create_multiregion_provider,
)
from .priority import (
    RequestScheduler,
    PrioritizedVisionProvider,
    PriorityQueue,
    HeapPriorityQueue,
    MultiLevelQueue,
    Priority,
    QueueStrategy,
    RequestStatus,
    PrioritizedRequest,
    QueueStats,
    QueueFullError,
    create_prioritized_provider,
)
from .transformation import (
    TransformationPipeline,
    TransformingVisionProvider,
    Transformer,
    RequestTransformer,
    ResponseTransformer,
    LambdaRequestTransformer,
    LambdaResponseTransformer,
    TransformStage,
    TransformPriority,
    TransformContext,
    TransformResult,
    PipelineStats,
    ConfidenceBoostTransformer,
    SummaryPrefixTransformer,
    DetailFilterTransformer,
    create_transforming_provider,
)
from .discovery import (
    CapabilityDiscovery,
    CapabilityAwareVisionProvider,
    Capability,
    CapabilityStatus,
    CapabilityInfo,
    CapabilityRequirement,
    ProviderCapabilities,
    MatchResult,
    get_capability_discovery,
    create_capability_aware_provider,
)
from .hot_reload import (
    HotReloadManager,
    HotReloadingVisionProvider,
    ConfigSource,
    FileConfigSource,
    DictConfigSource,
    HotReloadConfig,
    ConfigValidator,
    ReloadEvent,
    ReloadTrigger,
    ReloadStatus,
    ConfigVersion,
    create_hot_reloading_provider,
)
from .deduplication import (
    DeduplicationManager,
    DeduplicatingVisionProvider,
    DeduplicationConfig,
    DeduplicationStrategy,
    DeduplicationCache,
    DeduplicationStats,
    CachedResult,
    KeyGenerator,
    HashKeyGenerator,
    SizeHashKeyGenerator,
    HashAlgorithm as DeduplicationHashAlgorithm,
    get_deduplication_manager,
    create_deduplicating_provider,
)
from .versioning import (
    VersionRegistry,
    VersionedVisionProvider,
    SemanticVersion,
    ProviderVersion,
    VersionStatus,
    VersionConstraint,
    VersionHistory,
    CompatibilityLevel,
    get_version_registry,
    create_versioned_provider,
)
from .middleware import (
    MiddlewareChain,
    MiddlewareVisionProvider,
    Middleware,
    LambdaMiddleware,
    ConditionalMiddleware,
    MiddlewareContext,
    MiddlewareResult,
    MiddlewarePhase,
    MiddlewarePriority,
    MiddlewareChainStats,
    TimingMiddleware,
    LoggingMiddleware as MiddlewareLogging,
    MetadataMiddleware,
    create_middleware_provider,
)
from .circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerVisionProvider,
    CircuitBreakerConfig as AdvancedCircuitBreakerConfig,
    CircuitBreakerStats,
    CircuitBreakerError,
    CircuitState as AdvancedCircuitState,
    FailureType,
    RecoveryStrategy,
    SlidingWindow,
    get_circuit_breaker,
    create_circuit_breaker_provider,
)
from .retry_policy import (
    RetryPolicy,
    RetryVisionProvider,
    RetryPolicyConfig,
    RetryStats,
    RetryAttempt,
    RetryBudget,
    BackoffStrategy,
    JitterType,
    BackoffCalculator,
    FixedBackoff,
    ExponentialBackoff,
    LinearBackoff,
    FibonacciBackoff,
    create_retry_provider,
)
from .request_context import (
    RequestContext,
    ContextManager,
    ContextAwareVisionProvider,
    ContextScope,
    ContextSpan,
    BaggageItem,
    get_current_context as get_request_context,
    set_current_context as set_request_context,
    context_scope,
    get_context_manager,
    create_context_aware_provider,
)
from .provider_pool import (
    ProviderPool,
    PooledVisionProvider,
    PoolConfig,
    PoolState,
    PoolStats,
    PooledConnection,
    ConnectionState,
    ProviderFactory,
    SimpleProviderFactory,
    create_pooled_provider,
)
from .service_mesh import (
    ServiceMesh,
    MeshVisionProvider,
    ServiceRegistry,
    LoadBalancer as MeshLoadBalancer,
    TrafficManager,
    Sidecar,
    ServiceInstance,
    ServiceEndpoint,
    ServiceStatus,
    LoadBalancerPolicy,
    RetryPolicy as MeshRetryPolicy,
    CircuitState as MeshCircuitState,
    TrafficRule,
    MeshConfig,
    SidecarConfig,
    SidecarStats,
    create_mesh_provider,
)
from .distributed_tracing import (
    TracerProvider,
    DistributedTracer,
    TracingVisionProvider as DistributedTracingVisionProvider,
    TracingSpan,
    SpanContext,
    SpanEvent,
    SpanLink,
    SpanKind as DistributedSpanKind,
    SpanStatus as DistributedSpanStatus,
    TraceId,
    SpanId,
    TraceContext,
    Sampler,
    AlwaysOnSampler,
    AlwaysOffSampler,
    TraceIdRatioSampler,
    ParentBasedSampler,
    SamplingDecision,
    SpanExporter as DistributedSpanExporter,
    InMemorySpanExporter,
    ConsoleSpanExporter as DistributedConsoleSpanExporter,
    BatchSpanProcessor,
    Propagator,
    W3CTraceContextPropagator,
    B3Propagator,
    TracerConfig as DistributedTracerConfig,
    TracingStats,
    trace_span,
    create_tracing_provider as create_distributed_tracing_provider,
)
from .config_management import (
    ConfigurationManager,
    ConfigurableVisionProvider,
    ConfigProvider,
    DictConfigProvider,
    EnvironmentConfigProvider,
    FileConfigProvider,
    ConfigSchema,
    ConfigValue,
    ConfigChange,
    ConfigWatcher,
    ProfileManager as ConfigProfileManager,
    ConfigProfile,
    ConfigSnapshotManager,
    ConfigSnapshot,
    ConfigSource as ConfigSourceType,
    ConfigFormat,
    ValidationLevel,
    create_configurable_provider,
)
from .feature_flags import (
    FeatureFlagManager,
    FeatureFlagVisionProvider,
    FlagEvaluator,
    FlagStore,
    InMemoryFlagStore,
    FeatureFlag,
    FlagVariation,
    TargetingRule,
    PercentageRollout,
    EvaluationContext,
    EvaluationResult,
    FlagType,
    FlagStatus,
    TargetingOperator,
    FlagEvaluationCache,
    create_feature_flag_provider,
)
from .graceful_degradation import (
    DegradationManager,
    GracefulDegradationVisionProvider,
    FallbackChain,
    FallbackChainVisionProvider,
    FallbackProvider,
    StaticFallbackProvider,
    CachedFallbackProvider,
    DegradationPolicy,
    RecoveryManager,
    DegradationLevel,
    DegradationReason,
    RecoveryStrategy as DegradationRecoveryStrategy,
    DegradationState,
    DegradationMetrics,
    DegradationThresholds,
    DegradationConfig,
    FallbackResponse,
    create_graceful_provider,
    create_fallback_chain,
)
from .observability import (
    MetricsCollector,
    StructuredLogger,
    AlertManager,
    HealthChecker,
    SLOMonitor,
    ObservabilityContext,
    ObservableVisionProvider,
    MetricType as ObservabilityMetricType,
    LogLevel as ObservabilityLogLevel,
    AlertSeverity as ObservabilityAlertSeverity,
    AlertStatus,
    HealthStatus as ObservabilityHealthStatus,
    MetricValue as ObservabilityMetricValue,
    HistogramBucket,
    HistogramValue as ObservabilityHistogramValue,
    LogEntry,
    Alert,
    AlertRule,
    HealthCheck,
    SLI,
    SLO,
    create_observable_provider,
)
from .deployment import (
    DeploymentManager,
    DeploymentVisionProvider,
    TrafficRouter,
    BlueGreenDeployment,
    CanaryRelease,
    RollingUpdate,
    DeploymentStrategy,
    DeploymentPhase,
    EnvironmentType,
    TrafficSplitMethod,
    DeploymentVersion,
    DeploymentConfig,
    DeploymentMetrics as DeploymentMetricsData,
    DeploymentState,
    create_blue_green_provider,
    create_canary_provider,
)
from .multi_tenancy import (
    TenantManager,
    MultiTenantVisionProvider,
    QuotaManager as TenantQuotaManager,
    UsageTracker,
    TenantContext,
    TenantStore,
    InMemoryTenantStore,
    TenantStatus,
    TenantTier,
    IsolationLevel,
    QuotaType,
    ResourceQuota,
    TenantConfig,
    Tenant,
    TenantUsage,
    create_multi_tenant_provider,
)
from .compliance import (
    ComplianceManager,
    ComplianceVisionProvider,
    AuditLogger as ComplianceAuditLogger,
    PIIDetector,
    DataRetentionManager,
    AuditEventType as ComplianceAuditEventType,
    AuditSeverity as ComplianceAuditSeverity,
    ComplianceStandard,
    DataClassification,
    RetentionPolicy as ComplianceRetentionPolicy,
    AuditEvent,
    DataRetentionConfig,
    ComplianceRequirement,
    PIIDetectionResult,
    create_compliant_provider,
)
from .chaos_engineering import (
    ChaosManager,
    ChaosVisionProvider,
    FaultInjector,
    LatencyInjector,
    ErrorInjector,
    ChaosExperiment,
    FaultType,
    ExperimentStatus as ChaosExperimentStatus,
    TargetType,
    InjectionStrategy,
    FaultConfig,
    ExperimentConfig as ChaosExperimentConfig,
    ExperimentResult as ChaosExperimentResult,
    create_chaos_provider,
    create_experiment,
)
from .event_sourcing import (
    EventStore,
    InMemoryEventStore,
    SnapshotStore,
    SnapshotStore as InMemorySnapshotStore,  # Alias for compatibility
    Aggregate,
    Aggregate as AggregateRoot,  # Alias for compatibility
    VisionRequestAggregate,
    Projection,
    RequestCountProjection,
    LatencyProjection,
    Command,
    Query,
    CommandHandler,
    QueryHandler,
    GetStatisticsQuery as GetRequestStatsQuery,  # Alias
    GetStatisticsQueryHandler as GetRequestStatsHandler,  # Alias
    EventSourcedVisionProvider,
    Event,
    Snapshot,
    EventType,
    AggregateType,
    create_event_sourced_provider,
)
from .plugin_system import (
    PluginManager,
    PluginRegistry,
    PluginPipeline,
    PluggableVisionProvider,
    Plugin,
    VisionProviderPlugin,
    PreprocessorPlugin,
    PostprocessorPlugin,
    MiddlewarePlugin,
    HookManager,
    PluginDiscovery,
    PluginSandbox,
    PluginState,
    PluginType,
    HookPriority,
    PluginCapability,
    PluginMetadata,
    PluginInstance,
    HookRegistration,
    PluginEvent,
    create_plugin_manager,
    create_plugin_pipeline,
)
from .api_gateway import (
    ApiGateway,
    VisionApiGateway,
    Router,
    LoadBalancer as GatewayLoadBalancer,
    ApiVersionManager,
    ApiAggregator,
    GatewayMiddleware,
    LoggingMiddleware as GatewayLoggingMiddleware,
    CorsMiddleware,
    CompressionMiddleware,
    RequestTransformer as GatewayRequestTransformer,
    ResponseTransformer as GatewayResponseTransformer,
    HeaderInjectionTransformer,
    PathRewriteTransformer,
    JsonResponseTransformer,
    HttpMethod,
    LoadBalanceStrategy,
    ProtocolType,
    ResponseStatus,
    GatewayRequest,
    GatewayResponse,
    RouteConfig,
    ServiceEndpoint as GatewayServiceEndpoint,
    ApiVersion,
    create_api_gateway,
    create_vision_gateway,
    create_load_balancer as create_gateway_load_balancer,
)
from .distributed_lock import (
    LockManager,
    DistributedLock,
    InMemoryLock,
    ReentrantLock,
    ReadWriteLock,
    DistributedSemaphore,
    FencingTokenManager,
    LockedVisionProvider,
    LockType,
    LockState,
    LockAcquisitionResult,
    LockInfo,
    LockRequest,
    LockResult,
    DeadlockInfo,
    create_lock_manager,
    create_reentrant_lock,
    create_read_write_lock,
    create_semaphore,
)
from .workflow_engine import (
    WorkflowEngine,
    WorkflowBuilder,
    WorkflowVisionProvider,
    TaskHandler,
    VisionAnalysisTask,
    ConditionalTask,
    ParallelTask,
    SequentialTask,
    ImagePreprocessTask,
    ImageAnalysisTask,
    ResultAggregationTask,
    StateMachine,
    WorkflowStatus,
    TaskStatus,
    TriggerType,
    RetryPolicy as WorkflowRetryPolicy,
    TaskDefinition,
    WorkflowDefinition,
    TaskExecution,
    WorkflowExecution,
    WorkflowEvent,
    StateTransition,
    create_workflow_engine,
    create_workflow_builder,
    create_vision_workflow,
)
from .encryption import (
    EncryptionService,
    EncryptedVisionProvider,
    KeyManager,
    KeyStore,
    InMemoryKeyStore,
    Encryptor,
    SimpleAESEncryptor,
    Hasher,
    HMACAuthenticator,
    SecureStorage,
    EncryptionAlgorithm,
    KeyType,
    KeyStatus,
    HashAlgorithm as EncryptionHashAlgorithm,
    KeyMetadata,
    EncryptedData,
    SecureValue,
    create_encryption_service,
    create_encrypted_provider,
)
from .audit_logging import (
    AuditLogger as Phase11AuditLogger,
    AuditedVisionProvider,
    AuditStore,
    InMemoryAuditStore as Phase11InMemoryAuditStore,
    ComplianceTracker as Phase11ComplianceTracker,
    AuditTrail,
    AuditEventType as Phase11AuditEventType,
    AuditSeverity as Phase11AuditSeverity,
    ComplianceFramework,
    AuditActor,
    AuditResource,
    AuditEvent as Phase11AuditEvent,
    ComplianceRequirement as Phase11ComplianceRequirement,
    create_audit_logger as create_phase11_audit_logger,
    create_audited_provider,
    create_compliance_tracker as create_phase11_compliance_tracker,
)
from .data_pipeline import (
    Pipeline,
    PipelineBuilder,
    VisionPipelineProvider,
    ETLPipeline,
    BatchProcessor as PipelineBatchProcessor,
    DataSource,
    DataSink,
    InMemoryDataSource,
    InMemoryDataSink,
    Transformer as PipelineTransformer,
    MapTransformer,
    FilterTransformer,
    FieldExtractTransformer,
    EnrichTransformer,
    PipelineStageType,
    PipelineStatus,
    DataFormat,
    DataRecord,
    BatchResult as PipelineBatchResult,
    PipelineStage,
    PipelineConfig,
    create_pipeline,
    create_etl_pipeline,
    create_batch_processor as create_pipeline_batch_processor,
)
from .stream_processing import (
    Stream,
    StreamBuilder,
    StreamingVisionProvider as Phase11StreamingVisionProvider,
    Window,
    TumblingWindow,
    SlidingWindow,
    SessionWindow,
    CountWindow,
    WindowedStream,
    StreamOperator,
    MapOperator,
    FilterOperator,
    FlatMapOperator,
    KeyByOperator,
    Aggregator,
    SumAggregator,
    CountAggregator,
    AverageAggregator,
    MinAggregator,
    MaxAggregator,
    WindowType,
    TriggerType as StreamTriggerType,
    StreamState,
    StreamEvent as Phase11StreamEvent,
    WindowResult,
    create_stream,
    create_streaming_provider as create_phase11_streaming_provider,
)
from .data_validation import (
    Schema,
    SchemaBuilder,
    ValidatedVisionProvider,
    Validator,
    TypeValidator,
    RequiredValidator,
    RangeValidator,
    LengthValidator,
    PatternValidator,
    EnumValidator,
    CustomValidator,
    CompositeValidator,
    DataQualityChecker,
    ValidationSeverity as Phase11ValidationSeverity,
    ValidationStatus,
    DataType,
    ValidationError as Phase11ValidationError,
    ValidationResult as Phase11ValidationResult,
    FieldSchema,
    create_schema,
    create_validator,
    create_quality_checker,
    create_validated_provider,
)

# Phase 12: Advanced Analytics & ML Integration
from .ml_integration import (
    ModelRegistry,
    MLVisionProvider,
    InferenceEngine,
    InferencePipeline,
    ModelStore,
    InMemoryModelStore,
    FeatureExtractor,
    ImageFeatureExtractor,
    CompositeFeatureExtractor,
    MLModel,
    SimpleClassifier,
    EnsembleModel,
    ModelType,
    ModelStatus,
    InferenceMode,
    FeatureType,
    ModelMetadata,
    ModelVersion,
    Feature as MLFeature,
    FeatureVector,
    InferenceRequest,
    InferenceResult,
    PipelineStage as MLPipelineStage,
    PipelineConfig as MLPipelineConfig,
    create_model_registry,
    create_inference_engine,
    create_ml_provider,
    create_feature_extractor,
    create_simple_classifier,
    create_ensemble_model,
)
from .recommendations import (
    RecommendationEngine,
    RecommendationVisionProvider,
    SimilarityCalculator,
    ItemStore,
    InMemoryItemStore,
    InteractionStore,
    InMemoryInteractionStore,
    RecommendationStrategy,
    PopularityStrategy,
    ContentBasedStrategy,
    CollaborativeStrategy,
    RecommendationType,
    SimilarityMetric,
    InteractionType,
    Item,
    User as RecommendationUser,
    Interaction,
    Recommendation,
    RecommendationRequest,
    RecommendationResult,
    SimilarityResult,
    create_recommendation_engine,
    create_recommendation_provider,
    create_similarity_calculator,
    create_item,
    create_interaction,
)
from .anomaly_detection import (
    AnomalyDetectionEngine,
    AnomalyDetectionVisionProvider,
    AlertManager as AnomalyAlertManager,
    AnomalyDetector,
    ZScoreDetector,
    IQRDetector,
    ThresholdDetector,
    MovingAverageDetector,
    AnomalyType,
    DetectionMethod,
    AlertSeverity as AnomalySeverity,
    AlertStatus as AnomalyAlertStatus,
    DataPoint,
    Anomaly,
    Alert as AnomalyAlert,
    Threshold as AnomalyThreshold,
    DetectionConfig,
    DetectionResult,
    create_anomaly_engine,
    create_anomaly_provider,
    create_zscore_detector,
    create_iqr_detector,
    create_threshold_detector,
    create_moving_average_detector,
    create_alert_manager,
    create_threshold,
)
from .reporting import (
    ReportGenerator,
    ReportBuilder,
    ReportingVisionProvider,
    DashboardManager,
    ReportScheduler,
    ReportFormatter,
    JSONFormatter,
    MarkdownFormatter,
    CSVFormatter,
    HTMLFormatter,
    ReportType,
    ReportFormat,
    ChartType,
    ReportStatus,
    ScheduleFrequency,
    DataSeries,
    ChartConfig,
    ReportSection,
    ReportConfig,
    Report,
    DashboardWidget,
    Dashboard,
    ScheduledReport,
    ExportResult,
    create_report_generator,
    create_report_builder,
    create_dashboard_manager,
    create_report_scheduler,
    create_reporting_provider,
    create_chart_config,
    create_data_series,
    create_dashboard_widget,
)

# Phase 13: Advanced Distributed Systems & Messaging
from .message_queue import (
    MessageQueue,
    MessageBroker,
    MessageQueueVisionProvider,
    Publisher,
    Subscriber,
    DeadLetterQueue,
    Message,
    MessageStatus,
    DeliveryMode,
    QueueType,
    AckMode,
    MessageBatch,
    PublishResult,
    ConsumeResult,
    QueueConfig,
    QueueStats as MessageQueueStats,
    Subscription,
    create_message_queue,
    create_message_broker,
    create_mq_provider,
    create_message,
    create_dead_letter_queue,
)
from .distributed_cache import (
    DistributedCache,
    DistributedCacheVisionProvider,
    CacheManager,
    CacheShard,
    ConsistentHashRing,
    CacheNode,
    CacheStrategy,
    ConsistencyLevel,
    InvalidationStrategy,
    CacheNodeStatus,
    CacheEntry,
    CacheStats as DistributedCacheStats,
    CacheConfig,
    ShardInfo,
    create_distributed_cache,
    create_cache_manager,
    create_dcache_provider,
    create_cache_config,
    create_consistent_hash_ring,
)
from .saga_pattern import (
    SagaOrchestrator,
    SagaVisionProvider,
    SagaDefinition,
    SagaBuilder,
    CompensationManager,
    TransactionCoordinator,
    TransactionParticipant,
    SimpleParticipant,
    ChoreographySaga,
    SagaStep,
    SagaContext,
    SagaExecution,
    SagaStatus,
    StepStatus,
    create_saga_orchestrator,
    create_saga_builder,
    create_compensation_manager,
    create_transaction_coordinator,
    create_choreography_saga,
    create_saga_provider,
)
from .event_bus import (
    EventBus,
    EventDrivenVisionProvider,
    EventRouter,
    EventStore as EventBusStore,
    EventAggregator,
    CommandBus,
    QueryBus,
    EventHandler,
    FunctionEventHandler,
    Event as EventBusEvent,
    VisionEvent,
    ImageAnalyzedEvent,
    AnalysisFailedEvent,
    EventEnvelope,
    EventPriority,
    EventStatus,
    create_event_bus,
    create_event_router,
    create_event_store as create_event_bus_store,
    create_event_aggregator,
    create_command_bus,
    create_query_bus,
    create_event_provider,
)

# Phase 14: Advanced Security & Privacy (merged with Phase 19)
from .access_control import (
    RoleManager,
    AccessController as AccessControlManager,
    AccessControlVisionProvider,
    Role,
    Permission as AccessPermission,
    User as AccessUser,
    AccessDecision,
    AccessRequest,
    AccessResult,
    ACLResource as Resource,
    ACLResourceType as ResourceType,
    create_role_manager as create_role_manager_p14,
    create_access_controller as create_access_manager,
    create_access_control_provider as create_acl_provider,
    create_role as create_role_p14,
)
from .data_masking import (
    MaskingEngine,
    DataMaskingVisionProvider,
    PIIDetector,
    RegexPIIDetector,
    HeuristicPIIDetector,
    DataMasker,
    RedactionMasker,
    PartialMasker,
    HashMasker,
    TokenizeMasker,
    PseudonymizeMasker,
    PIIType,
    MaskingStrategy,
    SensitivityLevel,
    PIIMatch,
    MaskingRule,
    MaskingResult,
    DetectionReport,
    create_masking_engine,
    create_masking_provider,
    create_regex_detector,
    create_heuristic_detector,
    create_masking_rule,
    create_redaction_masker,
    create_partial_masker,
    create_hash_masker,
    create_tokenize_masker,
    create_pseudonymize_masker,
)
from .security_audit import (
    SecurityAuditManager,
    SecurityAuditVisionProvider,
    ThreatDetector,
    BruteForceDetector,
    AnomalyDetector as SecurityAnomalyDetector,
    IPReputationDetector,
    AuditLogger as SecurityAuditLogger,
    AlertManager as SecurityAlertManager,
    SecurityEventType,
    SeverityLevel as SecuritySeverityLevel,
    ThreatLevel,
    AlertStatus as SecurityAlertStatus,
    SecurityEvent,
    SecurityAlert,
    ThreatIndicator,
    AuditPolicy,
    SecurityMetrics,
    create_security_audit_manager,
    create_audit_provider as create_security_audit_provider,
    create_brute_force_detector,
    create_anomaly_detector as create_security_anomaly_detector,
    create_ip_reputation_detector,
    create_audit_logger as create_security_audit_logger,
    create_alert_manager as create_security_alert_manager,
    create_security_event,
    create_audit_policy,
)
from .key_management import (
    KeyManager as Phase14KeyManager,
    KeyManagedVisionProvider,
    KeyGenerator,
    KeyStore as Phase14KeyStore,
    InMemoryKeyStore as Phase14InMemoryKeyStore,
    EncryptedKeyStore,
    SecretsVault,
    KeyRotationPolicy,
    KeyType as Phase14KeyType,
    KeyStatus as Phase14KeyStatus,
    KeyAlgorithm,
    SecretType,
    CryptoKey,
    Secret,
    KeyAuditEntry,
    create_key_manager,
    create_key_managed_provider,
    create_key_generator,
    create_in_memory_key_store,
    create_encrypted_key_store,
    create_secrets_vault,
    create_rotation_policy,
    create_crypto_key,
)
from .privacy_compliance import (
    PrivacyComplianceManager,
    PrivacyComplianceVisionProvider,
    ConsentManager,
    ConsentStore,
    InMemoryConsentStore,
    DataSubjectRequestHandler,
    DataRetentionManager as PrivacyRetentionManager,
    ProcessingActivityLog,
    PrivacyRegulation,
    ConsentType,
    LegalBasis,
    DataSubjectRight,
    RequestStatus as PrivacyRequestStatus,
    Consent,
    DataSubjectRequest,
    DataRetentionPolicy,
    ProcessingActivity,
    PrivacyImpactAssessment,
    create_consent_manager,
    create_consent_store,
    create_request_handler,
    create_retention_manager as create_privacy_retention_manager,
    create_activity_log,
    create_compliance_manager as create_privacy_compliance_manager,
    create_compliance_provider,
)

# Phase 15: Advanced Analytics & Intelligence
from .predictive_analytics import (
    PredictiveEngine,
    PredictiveVisionProvider,
    DemandPredictor,
    AnomalyPredictor,
    TimeSeriesStore,
    TrendAnalyzer,
    MovingAverageModel,
    ExponentialSmoothingModel,
    PredictionType,
    ModelType as PredictionModelType,
    ForecastHorizon,
    TrendDirection,
    DataPoint,
    PredictionResult,
    TrendAnalysis,
    ForecastResult,
    ModelMetrics as PredictionModelMetrics,
    create_predictive_engine,
    create_predictive_provider,
    create_demand_predictor,
    create_anomaly_predictor,
)
from .intelligent_routing import (
    IntelligentRouter,
    RoutedVisionProvider,
    LoadBalancer,
    AdaptiveRouter,
    ContentAnalyzer,
    CapabilityMatchRule,
    LatencyConstraintRule,
    CostConstraintRule,
    RoutingStrategy,
    ProviderCapability,
    RequestPriority,
    ProviderStats,
    RoutingDecision,
    RoutingContext,
    ProviderConfig as RoutingProviderConfig,
    create_intelligent_router,
    create_routed_provider,
    create_provider_config,
    create_routing_context,
)
from .auto_scaling import (
    AutoScaler,
    AutoScaledVisionProvider,
    MetricsCollector,
    ScalingPredictor,
    ReactiveScaler,
    PredictiveScaler,
    ScheduledScaler,
    ScalingDirection,
    ScalingPolicy,
    ResourceType as ScalingResourceType,
    ScalingState,
    ScalingConfig,
    ScalingMetrics,
    ScalingDecision,
    ScalingEvent,
    CapacityPlan,
    create_scaling_config,
    create_auto_scaler,
    create_auto_scaled_provider,
    create_capacity_plan,
)
from .self_healing import (
    SelfHealingEngine,
    SelfHealingVisionProvider,
    HealthMonitor,
    IssueDetector,
    RecoveryPlanner,
    RecoveryExecutor,
    HealthStatus,
    IssueType,
    RecoveryAction,
    RecoveryStatus,
    HealthCheck,
    Issue,
    RecoveryPlan,
    RecoveryResult,
    HealingEvent,
    create_health_monitor,
    create_self_healing_engine,
    create_self_healing_provider,
    create_health_check,
)
from .knowledge_base import (
    KnowledgeBase,
    KnowledgeEnhancedVisionProvider,
    KnowledgeGraph,
    SemanticIndex,
    KnowledgeStore,
    EntityType,
    RelationType,
    SearchStrategy,
    Entity,
    Relationship,
    SearchResult as KnowledgeSearchResult,
    QueryResult as KnowledgeQueryResult,
    KnowledgeEntry,
    create_knowledge_graph,
    create_knowledge_base,
    create_knowledge_provider,
    create_entity,
    create_relationship,
)

# Phase 16: Advanced Integration & Extensibility
from .plugin_manager import (
    PluginManager,
    PluginVisionProvider,
    PluginRegistry,
    HookExecutor,
    PluginLoader,
    DependencyContainer,
    PluginType,
    PluginState,
    HookType,
    PluginMetadata,
    PluginInfo,
    HookResult,
    Plugin,
    VisionPlugin,
    ProviderPlugin,
    FilterPlugin,
    TransformerPlugin,
    create_plugin_manager,
    create_plugin_provider,
    create_dependency_container,
    create_plugin_metadata,
)
from .api_versioning import (
    ApiVersionManager,
    VersionedVisionProvider,
    SemanticVersion,
    VersionRegistry,
    DeprecationManager,
    VersionNegotiator,
    VersionRouter,
    VersionStatus,
    CompatibilityLevel,
    ChangeType as VersionChangeType,
    VersionInfo,
    ApiChange,
    DeprecationWarning as VersionDeprecationWarning,
    create_version_manager,
    create_versioned_provider,
    create_semantic_version,
    create_version_info,
)
from .sdk_generator import (
    SDKGenerator,
    SDKGeneratorVisionProvider,
    PythonGenerator,
    TypeScriptGenerator,
    OpenAPIGenerator,
    GraphQLSchemaGenerator,
    APIDefinitionBuilder,
    SDKLanguage,
    SpecFormat,
    HTTPMethod,
    ParameterLocation,
    DataType as SDKDataType,
    SchemaProperty,
    SchemaDefinition,
    ParameterDefinition,
    ResponseDefinition,
    EndpointDefinition,
    APIDefinition,
    GeneratedFile,
    SDKConfig,
    GenerationResult as SDKGenerationResult,
    create_sdk_generator,
    create_api_definition_builder,
    create_sdk_generator_provider,
    create_python_generator,
    create_typescript_generator,
    create_openapi_generator,
    create_graphql_generator,
)
from .integration_hub import (
    IntegrationHub,
    IntegrationHubVisionProvider,
    Connector,
    RESTConnector,
    WebSocketConnector,
    WebhookManager as IntegrationWebhookManager,
    RateLimiter as IntegrationRateLimiter,
    DataTransformer,
    ConnectorType,
    AuthenticationType,
    ConnectorStatus,
    WebhookEventType,
    DataFormat,
    AuthCredentials,
    RateLimitConfig as IntegrationRateLimitConfig,
    ConnectorConfig,
    WebhookConfig as IntegrationWebhookConfig,
    WebhookPayload,
    IntegrationHealth,
    DataMapping,
    TransformResult,
    create_integration_hub,
    create_rest_connector,
    create_websocket_connector,
    create_webhook_manager as create_integration_webhook_manager,
    create_rate_limiter as create_integration_rate_limiter,
    create_data_transformer,
    create_integration_hub_provider,
)
from .documentation_generator import (
    DocumentationGenerator,
    DocumentedVisionProvider,
    MarkdownGenerator,
    HTMLGenerator,
    CodeExtractor,
    DocstringParser,
    DocFormat,
    DocSection,
    ChangeType,
    ParameterType as DocParameterType,
    ParameterDoc,
    ReturnDoc,
    ExceptionDoc,
    MethodDoc,
    ClassDoc,
    ModuleDoc,
    ChangeLogEntry,
    ChangeLog,
    DocConfig,
    GeneratedDoc,
    DocGenerationResult,
    create_documentation_generator,
    create_markdown_generator,
    create_html_generator,
    create_code_extractor,
    create_docstring_parser,
    create_documented_provider,
)

# Phase 17: Advanced Observability & Monitoring
from .metrics_dashboard import (
    MetricCollector,
    DashboardManager as MetricsDashboardManager,
    MetricStreamer,
    CustomMetricBuilder,
    MetricsDashboardVisionProvider,
    MetricType as DashboardMetricType,
    AggregationType,
    WidgetType,
    TimeRange,
    RefreshInterval,
    MetricDefinition,
    MetricValue as MetricDataPoint,
    MetricSeries as TimeSeriesData,
    WidgetConfig as MetricsDashboardWidget,
    DashboardConfig as MetricsDashboardConfig,
    create_metric_collector,
    create_dashboard_manager as create_metrics_dashboard_manager,
    create_metric_streamer,
    create_custom_metric_builder,
    create_metrics_dashboard_provider,
)
from .alert_manager import (
    AlertManager as Phase17AlertManager,
    AlertEvaluator,
    AlertManagerVisionProvider,
    AlertSeverity as Phase17AlertSeverity,
    AlertState,
    NotificationChannel,
    ComparisonOperator,
    EscalationAction,
    AlertRule as Phase17AlertRule,
    AlertCondition,
    Alert as AlertInstance,
    NotificationConfig,
    EscalationPolicy,
    SilenceRule,
    InhibitionRule,
    create_alert_manager as create_phase17_alert_manager,
    create_alert_rule as create_phase17_alert_rule,
    create_notification_channel,
    create_silence,
    create_escalation_policy,
    create_alert_manager_provider,
)
from .log_aggregator import (
    LogAggregator,
    LogStore as AggregatorLogStore,
    LogCorrelator,
    PatternDetector,
    LogAggregatorVisionProvider,
    LogLevel as AggregatorLogLevel,
    LogSource,
    ParserType,
    AggregationMode,
    LogEntry as AggregatorLogEntry,
    LogFilter,
    CorrelatedLogs as CorrelationResult,
    LogPattern,
    LogStats,
    RetentionPolicy as RetentionConfig,
    create_log_aggregator,
    create_json_parser,
    create_regex_parser,
    create_retention_policy as create_log_retention_policy,
    create_log_aggregator_provider,
)
from .apm_integration import (
    APMManager,
    SpanTracker,
    TransactionTracker,
    PerformanceAnalyzer,
    ErrorTracker,
    DependencyTracker,
    APMVisionProvider,
    TransactionType,
    SpanKind as APMSpanKind,
    SpanStatus as APMSpanStatus,
    APMProvider,
    ProfileType,
    Transaction,
    Span as APMSpan,
    ErrorInfo as ErrorRecord,
    DependencyInfo as DependencyRecord,
    PerformanceMetrics as APMPerformanceMetrics,
    APMConfig,
    create_apm_manager,
    create_apm_config,
    create_apm_provider,
)
from .sla_monitor import (
    SLAMonitor,
    SLATracker,
    UptimeTracker,
    SLAReporter,
    SLAMonitorVisionProvider,
    SLAType,
    SLAStatus,
    UptimeStatus,
    ReportPeriod,
    CheckType,
    SLADefinition,
    SLAMeasurement,
    UptimeCheck,
    IncidentRecord as UptimeIncident,
    SLAComplianceReport as SLAReport,
    create_sla_monitor,
    create_sla_definition,
    create_uptime_check,
    create_sla_monitor_provider,
)

# Phase 18: Advanced ML Pipeline & AutoML
from .automl_engine import (
    AutoMLEngine,
    HyperparameterOptimizer,
    RandomSearchOptimizer,
    BayesianOptimizer,
    ModelSelector,
    NeuralArchitectureSearch,
    FeatureSelector as AutoMLFeatureSelector,
    EnsembleBuilder,
    AutoMLVisionProvider,
    SearchStrategy,
    OptimizationObjective,
    ModelType as AutoMLModelType,
    TaskType as AutoMLTaskType,
    TrialStatus,
    EarlyStoppingStrategy,
    HyperparameterSpace,
    TrialResult,
    SearchConfig,
    ModelCandidate,
    EnsembleConfig,
    AutoMLResult,
    create_automl_engine,
    create_search_config,
    create_hyperparameter_space,
    create_model_selector,
    create_nas,
    create_feature_selector as create_automl_feature_selector,
    create_ensemble_builder,
    create_automl_provider,
)
from .feature_store import (
    FeatureRegistry,
    FeatureStore,
    FeatureComputer,
    FeatureValidator as FeatureStoreValidator,
    FeatureStatisticsComputer,
    FeatureStoreVisionProvider,
    FeatureType,
    FeatureStatus,
    ComputationMode,
    TransformationType,
    AggregationWindow,
    DataQualityCheck,
    FeatureDefinition,
    FeatureValue,
    FeatureGroup,
    FeatureTransformation,
    FeatureLineage,
    FeatureStatistics,
    QualityReport as FeatureQualityReport,
    create_feature_registry,
    create_feature_store,
    create_feature_definition,
    create_feature_group,
    create_feature_transformation,
    create_feature_computer,
    create_feature_validator,
    create_feature_store_provider,
)
from .model_registry import (
    ModelRegistry,
    ModelDeployer,
    ABTestManager,
    ApprovalWorkflow,
    ModelValidator as ModelRegistryValidator,
    ModelRegistryVisionProvider,
    ModelStage,
    ModelStatus as ModelRegistryStatus,
    DeploymentStrategy,
    ServingFormat,
    ApprovalStatus,
    MetricType as ModelMetricType,
    ModelVersion,
    ModelMetadata,
    ModelLineage,
    DeploymentConfig,
    Deployment,
    ABTestConfig,
    ABTestResult,
    ApprovalRequest,
    create_model_registry,
    create_model_version,
    create_model_metadata,
    create_deployment_config,
    create_ab_test_config,
    create_model_deployer,
    create_ab_test_manager,
    create_approval_workflow,
    create_model_registry_provider,
)
from .pipeline_orchestrator import (
    PipelineOrchestrator,
    DAGBuilder,
    TaskExecutor,
    PipelineScheduler,
    PipelineTemplate,
    PipelineOrchestratorVisionProvider,
    TaskStatus as PipelineTaskStatus,
    PipelineStatus,
    TriggerType,
    RetryPolicy,
    ExecutionMode,
    ResourceType,
    TaskDefinition,
    TaskInstance,
    PipelineDefinition,
    PipelineRun,
    DAGNode,
    ScheduleConfig,
    ResourceRequirements,
    create_pipeline_orchestrator,
    create_pipeline_definition,
    create_task_definition,
    create_dag_builder,
    create_task_executor,
    create_pipeline_scheduler,
    create_schedule_config,
    create_pipeline_template,
    create_pipeline_orchestrator_provider,
)
from .experiment_tracker import (
    ExperimentTracker,
    ExperimentStore,
    RunContext,
    MetricAggregator,
    HyperparameterAnalyzer,
    ExperimentTrackerVisionProvider,
    RunStatus,
    MetricGoal,
    ArtifactType,
    ComparisonMode,
    TagType,
    Experiment,
    Run as ExperimentRun,
    Parameter as ExperimentParameter,
    Metric as ExperimentMetric,
    MetricHistory,
    Artifact as ExperimentArtifact,
    ComparisonResult,
    SearchQuery,
    create_experiment_tracker,
    create_experiment,
    create_run as create_experiment_run,
    create_metric as create_experiment_metric,
    create_parameter as create_experiment_parameter,
    create_artifact as create_experiment_artifact,
    create_search_query,
    create_metric_aggregator,
    create_hyperparameter_analyzer,
    create_experiment_tracker_provider,
)
# Phase 19: Advanced Security & Compliance
from .security_scanner import (
    SecurityScanner,
    CodeScanner,
    DependencyScanner,
    ThreatDetector,
    RiskAssessor,
    SecurityScannerVisionProvider,
    VulnerabilitySeverity,
    ScanType,
    ThreatCategory,
    ScanStatus,
    RemediationPriority,
    RiskLevel as SecurityRiskLevel,
    Vulnerability,
    ScanConfig,
    ScanResult,
    ThreatIndicator,
    RiskAssessment,
    SecurityPolicy,
    create_security_scanner,
    create_scan_config,
    create_vulnerability,
    create_threat_indicator,
    create_security_policy,
    create_code_scanner,
    create_dependency_scanner,
    create_threat_detector,
    create_risk_assessor,
    create_security_scanner_provider,
)
from .access_control import (
    AccessController,
    UserManager,
    RoleManager,
    SessionManager,
    APIKeyManager,
    AccessControlVisionProvider,
    Permission,
    RoleType,
    AuthMethod,
    SessionStatus,
    AccessDecision,
    ACLResourceType,
    User as ACLUser,
    Role as ACLRole,
    ACLResource,
    Session as ACLSession,
    APIKey,
    AccessRequest,
    AccessResult,
    Tenant,
    create_access_controller,
    create_user as create_acl_user,
    create_role as create_acl_role,
    create_acl_resource,
    create_access_request,
    create_user_manager,
    create_role_manager,
    create_session_manager,
    create_api_key_manager,
    create_access_control_provider,
)
from .audit_logger import (
    AuditLogger,
    ComplianceAuditLogger,
    MemoryAuditStore,
    AuditLoggerVisionProvider,
    AuditEventType,
    AuditSeverity,
    AuditCategory,
    LogDestination,
    RetentionPeriod,
    AuditEvent,
    AuditQuery,
    AuditSummary,
    AuditPolicy,
    AuditAlert,
    LogIntegrity,
    create_audit_logger,
    create_compliance_audit_logger,
    create_audit_event,
    create_audit_query,
    create_audit_policy,
    create_audit_alert,
    create_memory_audit_store,
    create_audit_logger_provider,
)
from .encryption_manager import (
    EncryptionManager,
    KeyGenerator,
    Encryptor,
    KeyRotationManager,
    MemoryKeyStore,
    EncryptionManagerVisionProvider,
    EncryptionAlgorithm,
    KeyType,
    KeyStatus,
    KeyPurpose,
    HashAlgorithm,
    EncryptionKey,
    EncryptedData,
    KeyPolicy,
    Certificate,
    KeyRotationEvent,
    create_encryption_manager,
    create_memory_key_store,
    create_key_generator,
    create_encryptor,
    create_key_policy,
    create_encryption_manager_provider,
)
from .compliance_checker import (
    ComplianceChecker,
    ControlRegistry,
    ControlAssessor,
    PolicyEngine,
    ComplianceReporter,
    DataInventory,
    ComplianceCheckerVisionProvider,
    ComplianceFramework,
    ComplianceStatus,
    ControlCategory,
    RiskLevel as ComplianceRiskLevel,
    DataClassification,
    PolicyType,
    ComplianceControl,
    ControlAssessment,
    CompliancePolicy,
    PolicyViolation,
    ComplianceReport,
    DataInventoryItem,
    PrivacyImpactAssessment,
    create_compliance_checker,
    create_compliance_control,
    create_compliance_policy,
    create_data_inventory_item,
    create_privacy_impact_assessment,
    create_control_registry,
    create_policy_engine,
    create_data_inventory,
    create_compliance_checker_provider,
)

# Phase 20: Advanced Integration & Extensibility - Webhook Handler
from .webhook_handler import (
    # Classes
    WebhookManager as WebhookManagerP20,
    WebhookRegistry as WebhookRegistryP20,
    WebhookDeliveryService,
    WebhookRateLimiter,
    WebhookSignature,
    WebhookVisionProvider,
    # Enums
    WebhookEventType as WebhookEventTypeP20,
    WebhookStatus,
    DeliveryStatus,
    SignatureAlgorithm,
    # Dataclasses
    WebhookConfig as WebhookConfigP20,
    WebhookRegistration,
    WebhookEvent,
    DeliveryAttempt,
    DeliveryRecord,
    # Factory functions
    create_webhook_config as create_webhook_config_p20,
    create_webhook_manager as create_webhook_manager_p20,
    create_webhook_event,
)

# Phase 21: Advanced Observability & Telemetry - Observability Hub
from .observability_hub import (
    # Main orchestration classes
    ObservabilityHub,
    ObservableVisionProvider,
    # Component classes
    MetricsCollector,
    TraceManager,
    HealthMonitor,
    AlertManager as AlertManagerP21,
    SLOTracker,
    AnomalyDetector,
    # Enums
    MetricType,
    HealthStatus as HealthStatusP21,
    AlertSeverity as AlertSeverityP21,
    AlertState,
    TraceStatus,
    SLOStatus,
    AnomalyType,
    # Dataclasses
    MetricPoint,
    MetricSeries,
    SpanContext,
    Span,
    HealthCheck as HealthCheckP21,
    Alert as AlertP21,
    SLODefinition,
    SLOResult,
    Anomaly,
    ObservabilityConfig,
    # Factory functions
    create_observability_hub,
    create_metrics_collector,
    create_trace_manager,
    create_health_monitor,
    create_alert_manager as create_alert_manager_p21,
    create_slo_definition,
    create_observable_provider,
)

# Phase 22: Advanced Security & Governance - Security Governance Hub
from .security_governance import (
    # Main orchestration classes
    SecurityGovernanceHub,
    SecureVisionProvider,
    # Component classes
    PolicyEngine,
    DataClassificationManager,
    KeyManager,
    SecretManager,
    ThreatIntelManager,
    SecurityEventCorrelator,
    SecurityPostureAssessor,
    # Enums
    DataClassification,
    PolicyType as PolicyTypeP22,
    PolicyStatus as PolicyStatusP22,
    PolicyAction,
    EncryptionAlgorithm,
    KeyStatus,
    SecretType,
    ThreatLevel,
    SecurityEventType,
    PostureStatus,
    # Dataclasses
    SecurityPolicy,
    PolicyEvaluation,
    DataClassificationRule,
    EncryptionKey,
    Secret,
    ThreatIndicator,
    SecurityEvent,
    SecurityPosture,
    GovernanceConfig,
    # Factory functions
    create_governance_config,
    create_security_governance_hub,
    create_security_policy,
    create_classification_rule,
    create_threat_indicator,
    create_secure_provider,
)

# Phase 23: Intelligent Automation & Self-Optimization
from .intelligent_automation import (
    # Main orchestration classes
    IntelligentAutomationHub,
    AutomatedVisionProvider,
    # Component classes
    DecisionEngine,
    SelfTuner,
    IntelligentScheduler,
    LoadManager,
    PerformancePredictor,
    AutoRemediation,
    PatternLearner,
    # Enums
    DecisionType,
    DecisionConfidence,
    TuningStrategy,
    TuningStatus,
    SchedulerPriority,
    TaskState as TaskStateP23,
    LoadLevel,
    RemediationAction,
    PredictionType,
    LearningMode,
    # Dataclasses
    Decision,
    DecisionRule,
    TuningParameter,
    TuningSession,
    ScheduledTask,
    ResourcePool,
    LoadMetrics,
    Remediation,
    Prediction,
    LearningPattern,
    AutomationConfig,
    # Factory functions
    create_automation_config,
    create_intelligent_automation_hub,
    create_decision_rule,
    create_load_metrics,
    create_automated_provider,
)

# Phase 24: Advanced Data Management & Lifecycle
from .data_lifecycle import (
    # Main orchestration classes
    DataLifecycleHub,
    ManagedVisionProvider,
    # Component classes
    VersionManager,
    LineageTracker,
    QualityManager,
    RetentionManager,
    DataCatalog,
    TransformationTracker,
    # Enums
    DataState,
    VersionType,
    LineageRelation,
    QualityDimension,
    QualityLevel,
    RetentionAction,
    CatalogEntryType,
    TransformationType,
    AccessLevel,
    # Dataclasses
    DataVersion,
    LineageNode,
    LineageEdge,
    QualityRule,
    QualityResult,
    QualityReport,
    RetentionPolicy,
    RetentionResult,
    CatalogEntry,
    TransformationRecord,
    DataAsset,
    LifecycleConfig,
    # Factory functions
    create_lifecycle_config,
    create_data_lifecycle_hub,
    create_quality_rule,
    create_retention_policy,
    create_managed_provider,
)

__all__ = [
    # Models
    "VisionAnalyzeRequest",
    "VisionAnalyzeResponse",
    "VisionDescription",
    "OcrResult",
    # Base classes
    "VisionProvider",
    # Manager
    "VisionManager",
    # Stub provider
    "DeepSeekStubProvider",
    "create_stub_provider",
    # DeepSeek provider
    "DeepSeekVisionProvider",
    "create_deepseek_provider",
    # OpenAI provider
    "OpenAIVisionProvider",
    "create_openai_provider",
    # Anthropic provider
    "AnthropicVisionProvider",
    "create_anthropic_provider",
    # Factory
    "create_vision_provider",
    "get_vision_provider",
    "get_available_providers",
    # Exceptions
    "VisionError",
    "VisionProviderError",
    "VisionInputError",
    # Resilience
    "ResilientVisionProvider",
    "RetryConfig",
    "CircuitBreakerConfig",
    "CircuitState",
    "CircuitOpenError",
    "ProviderMetrics",
    "create_resilient_provider",
    # Cache
    "VisionCache",
    "CachedVisionProvider",
    "CacheStats",
    "create_cached_provider",
    # Rate Limiting
    "RateLimitConfig",
    "RateLimitStats",
    "RateLimitError",
    "RateLimitedVisionProvider",
    "TokenBucketRateLimiter",
    "create_rate_limited_provider",
    # Batch Processing
    "BatchProcessor",
    "BatchResult",
    "BatchProgress",
    "process_images_batch",
    # Comparison
    "ProviderComparator",
    "ComparisonResult",
    "SelectionStrategy",
    "compare_providers",
    # Streaming
    "StreamingVisionProvider",
    "StreamEvent",
    "StreamEventType",
    "StreamConfig",
    "BatchStreamProcessor",
    "stream_analysis",
    "generate_sse_stream",
    "create_streaming_provider",
    # Prompts
    "PromptManager",
    "PromptTemplate",
    "PromptConfig",
    "PromptType",
    "get_prompt_manager",
    "get_prompts",
    "register_custom_template",
    "BUILTIN_TEMPLATES",
    # Cost Tracking
    "CostTracker",
    "CostTrackedVisionProvider",
    "PricingTier",
    "UsageRecord",
    "UsageSummary",
    "BudgetConfig",
    "get_cost_tracker",
    "create_cost_tracked_provider",
    # Webhooks
    "WebhookManager",
    "WebhookVisionProvider",
    "WebhookConfig",
    "WebhookEvent",
    "WebhookEventType",
    "WebhookStatus",
    "DeliveryResult",
    "get_webhook_manager",
    "create_webhook_provider",
    # Persistence
    "ResultPersistence",
    "PersistentVisionProvider",
    "StorageProvider",
    "InMemoryStorage",
    "StorageBackend",
    "AnalysisRecord",
    "QueryFilter",
    "QueryResult",
    "get_persistence",
    "create_persistent_provider",
    # Analytics
    "VisionAnalytics",
    "ProviderStats",
    "TimeBucket",
    "TrendData",
    "TimeGranularity",
    "AnalyticsReport",
    "create_analytics",
    # Failover
    "FailoverManager",
    "FailoverVisionProvider",
    "ProviderEndpoint",
    "ProviderHealth",
    "FailoverStrategy",
    "FailoverConfig",
    "FailoverResult",
    "create_failover_provider",
    # Health Monitoring
    "HealthMonitor",
    "HealthAwareVisionProvider",
    "HealthMetrics",
    "HealthStatus",
    "HealthAlert",
    "AlertSeverity",
    "HealthCheckConfig",
    "HealthDashboard",
    "get_health_monitor",
    "create_health_aware_provider",
    # Preprocessing
    "ImagePreprocessor",
    "ImageValidator",
    "PreprocessingVisionProvider",
    "PreprocessingConfig",
    "ImageFormat",
    "ImageInfo",
    "ValidationResult",
    "create_preprocessing_provider",
    # Load Balancing
    "LoadBalancer",
    "LoadBalancedVisionProvider",
    "LoadBalancingAlgorithm",
    "LoadBalancerConfig",
    "LoadBalancerStats",
    "ProviderNode",
    "create_load_balanced_provider",
    # Logging Middleware
    "LoggingMiddleware",
    "LoggingVisionProvider",
    "LoggingConfig",
    "LogLevel",
    "LogDestination",
    "RequestLog",
    "ResponseLog",
    "PerformanceMetrics",
    "LogHandler",
    "ConsoleLogHandler",
    "FileLogHandler",
    "JSONLogHandler",
    "CallbackLogHandler",
    "get_logging_middleware",
    "create_logging_provider",
    # Configuration Profiles
    "ProfileManager",
    "ProfileConfig",
    "ProviderConfig",
    "ProfileType",
    "ProviderType",
    "ProfileRetryConfig",
    "ProfileRateLimitConfig",
    "ProfileCacheConfig",
    "ProfileCircuitBreakerConfig",
    "TimeoutConfig",
    "ProfileEnvironmentLoader",
    "get_profile_manager",
    "get_profile",
    "create_profile",
    # Tracing
    "Tracer",
    "TracingVisionProvider",
    "Span",
    "SpanStatus",
    "SpanKind",
    "RequestContext",
    "SpanExporter",
    "ConsoleSpanExporter",
    "TracerConfig",
    "get_current_context",
    "set_current_context",
    "get_tracer",
    "create_tracing_provider",
    # Metrics Export
    "MetricsExporter",
    "MetricsVisionProvider",
    "MetricType",
    "MetricValue",
    "HistogramValue",
    "MetricBackend",
    "InMemoryMetricBackend",
    "CallbackMetricBackend",
    "MetricsConfig",
    "get_metrics_exporter",
    "create_metrics_provider",
    # Image Embedding/Similarity
    "ImageEmbedder",
    "SimilarityIndex",
    "SimilarityVisionProvider",
    "HashAlgorithm",
    "ImageHash",
    "EmbeddingVector",
    "ImageRecord",
    "SimilarityResult",
    "CryptographicHashGenerator",
    "PerceptualHashGenerator",
    "create_similarity_provider",
    # Quotas and Throttling
    "QuotaManager",
    "Throttler",
    "QuotaVisionProvider",
    "QuotaPeriod",
    "ThrottleStrategy",
    "QuotaAction",
    "QuotaLimit",
    "QuotaUsage",
    "ThrottleConfig",
    "ThrottleState",
    "QuotaCheckResult",
    "ProviderQuotaConfig",
    "QUOTA_PRESETS",
    "THROTTLE_PRESETS",
    "get_quota_preset",
    "get_throttle_preset",
    "create_quota_provider",
    # A/B Testing
    "ExperimentManager",
    "ABTestingVisionProvider",
    "ExperimentConfig",
    "ExperimentStatus",
    "ExperimentResult",
    "ExperimentAnalysis",
    "Variant",
    "VariantType",
    "VariantStats",
    "AllocationStrategy",
    "StatisticalMethod",
    "get_experiment_manager",
    "create_ab_testing_provider",
    # Response Validation
    "ResponseValidator",
    "ValidatingVisionProvider",
    "ValidationSchema",
    "ValidationRule",
    "ValidationResult",
    "ValidationIssue",
    "ValidationSeverity",
    "ValidationRuleType",
    "ValidationStats",
    "ValidationError",
    "STANDARD_SCHEMA",
    "STRICT_SCHEMA",
    "OCR_SCHEMA",
    "create_validating_provider",
    # Audit Logging
    "AuditLogger",
    "AuditingVisionProvider",
    "AuditEntry",
    "AuditContext",
    "AuditConfig",
    "AuditEventType",
    "AuditLevel",
    "AuditStorage",
    "InMemoryAuditStorage",
    "RetentionPolicy",
    "get_audit_logger",
    "create_auditing_provider",
    # Multi-Region Routing
    "RegionRouter",
    "MultiRegionVisionProvider",
    "Region",
    "RegionConfig",
    "RegionHealth",
    "RegionStatus",
    "RoutingStrategy",
    "RoutingDecision",
    "LatencyMeasurer",
    "create_multiregion_provider",
    # Request Prioritization
    "RequestScheduler",
    "PrioritizedVisionProvider",
    "PriorityQueue",
    "HeapPriorityQueue",
    "MultiLevelQueue",
    "Priority",
    "QueueStrategy",
    "RequestStatus",
    "PrioritizedRequest",
    "QueueStats",
    "QueueFullError",
    "create_prioritized_provider",
    # Transformation Pipeline
    "TransformationPipeline",
    "TransformingVisionProvider",
    "Transformer",
    "RequestTransformer",
    "ResponseTransformer",
    "LambdaRequestTransformer",
    "LambdaResponseTransformer",
    "TransformStage",
    "TransformPriority",
    "TransformContext",
    "TransformResult",
    "PipelineStats",
    "ConfidenceBoostTransformer",
    "SummaryPrefixTransformer",
    "DetailFilterTransformer",
    "create_transforming_provider",
    # Capability Discovery
    "CapabilityDiscovery",
    "CapabilityAwareVisionProvider",
    "Capability",
    "CapabilityStatus",
    "CapabilityInfo",
    "CapabilityRequirement",
    "ProviderCapabilities",
    "MatchResult",
    "get_capability_discovery",
    "create_capability_aware_provider",
    # Hot Reload
    "HotReloadManager",
    "HotReloadingVisionProvider",
    "ConfigSource",
    "FileConfigSource",
    "DictConfigSource",
    "HotReloadConfig",
    "ConfigValidator",
    "ReloadEvent",
    "ReloadTrigger",
    "ReloadStatus",
    "ConfigVersion",
    "create_hot_reloading_provider",
    # Deduplication
    "DeduplicationManager",
    "DeduplicatingVisionProvider",
    "DeduplicationConfig",
    "DeduplicationStrategy",
    "DeduplicationCache",
    "DeduplicationStats",
    "CachedResult",
    "KeyGenerator",
    "HashKeyGenerator",
    "SizeHashKeyGenerator",
    "DeduplicationHashAlgorithm",
    "get_deduplication_manager",
    "create_deduplicating_provider",
    # Versioning
    "VersionRegistry",
    "VersionedVisionProvider",
    "SemanticVersion",
    "ProviderVersion",
    "VersionStatus",
    "VersionConstraint",
    "VersionHistory",
    "CompatibilityLevel",
    "get_version_registry",
    "create_versioned_provider",
    # Middleware Chain
    "MiddlewareChain",
    "MiddlewareVisionProvider",
    "Middleware",
    "LambdaMiddleware",
    "ConditionalMiddleware",
    "MiddlewareContext",
    "MiddlewareResult",
    "MiddlewarePhase",
    "MiddlewarePriority",
    "MiddlewareChainStats",
    "TimingMiddleware",
    "MiddlewareLogging",
    "MetadataMiddleware",
    "create_middleware_provider",
    # Advanced Circuit Breaker
    "CircuitBreaker",
    "CircuitBreakerVisionProvider",
    "AdvancedCircuitBreakerConfig",
    "CircuitBreakerStats",
    "CircuitBreakerError",
    "AdvancedCircuitState",
    "FailureType",
    "RecoveryStrategy",
    "SlidingWindow",
    "get_circuit_breaker",
    "create_circuit_breaker_provider",
    # Retry Policy
    "RetryPolicy",
    "RetryVisionProvider",
    "RetryPolicyConfig",
    "RetryStats",
    "RetryAttempt",
    "RetryBudget",
    "BackoffStrategy",
    "JitterType",
    "BackoffCalculator",
    "FixedBackoff",
    "ExponentialBackoff",
    "LinearBackoff",
    "FibonacciBackoff",
    "create_retry_provider",
    # Request Context
    "RequestContext",
    "ContextManager",
    "ContextAwareVisionProvider",
    "ContextScope",
    "ContextSpan",
    "BaggageItem",
    "get_request_context",
    "set_request_context",
    "context_scope",
    "get_context_manager",
    "create_context_aware_provider",
    # Provider Pool
    "ProviderPool",
    "PooledVisionProvider",
    "PoolConfig",
    "PoolState",
    "PoolStats",
    "PooledConnection",
    "ConnectionState",
    "ProviderFactory",
    "SimpleProviderFactory",
    "create_pooled_provider",
    # Service Mesh
    "ServiceMesh",
    "MeshVisionProvider",
    "ServiceRegistry",
    "MeshLoadBalancer",
    "TrafficManager",
    "Sidecar",
    "ServiceInstance",
    "ServiceEndpoint",
    "ServiceStatus",
    "LoadBalancerPolicy",
    "MeshRetryPolicy",
    "MeshCircuitState",
    "TrafficRule",
    "MeshConfig",
    "SidecarConfig",
    "SidecarStats",
    "create_mesh_provider",
    # Distributed Tracing
    "TracerProvider",
    "DistributedTracer",
    "DistributedTracingVisionProvider",
    "TracingSpan",
    "SpanContext",
    "SpanEvent",
    "SpanLink",
    "DistributedSpanKind",
    "DistributedSpanStatus",
    "TraceId",
    "SpanId",
    "TraceContext",
    "Sampler",
    "AlwaysOnSampler",
    "AlwaysOffSampler",
    "TraceIdRatioSampler",
    "ParentBasedSampler",
    "SamplingDecision",
    "DistributedSpanExporter",
    "InMemorySpanExporter",
    "DistributedConsoleSpanExporter",
    "BatchSpanProcessor",
    "Propagator",
    "W3CTraceContextPropagator",
    "B3Propagator",
    "DistributedTracerConfig",
    "TracingStats",
    "trace_span",
    "create_distributed_tracing_provider",
    # Configuration Management
    "ConfigurationManager",
    "ConfigurableVisionProvider",
    "ConfigProvider",
    "DictConfigProvider",
    "EnvironmentConfigProvider",
    "FileConfigProvider",
    "ConfigSchema",
    "ConfigValue",
    "ConfigChange",
    "ConfigWatcher",
    "ConfigProfileManager",
    "ConfigProfile",
    "ConfigSnapshotManager",
    "ConfigSnapshot",
    "ConfigSourceType",
    "ConfigFormat",
    "ValidationLevel",
    "create_configurable_provider",
    # Feature Flags
    "FeatureFlagManager",
    "FeatureFlagVisionProvider",
    "FlagEvaluator",
    "FlagStore",
    "InMemoryFlagStore",
    "FeatureFlag",
    "FlagVariation",
    "TargetingRule",
    "PercentageRollout",
    "EvaluationContext",
    "EvaluationResult",
    "FlagType",
    "FlagStatus",
    "TargetingOperator",
    "FlagEvaluationCache",
    "create_feature_flag_provider",
    # Graceful Degradation
    "DegradationManager",
    "GracefulDegradationVisionProvider",
    "FallbackChain",
    "FallbackChainVisionProvider",
    "FallbackProvider",
    "StaticFallbackProvider",
    "CachedFallbackProvider",
    "DegradationPolicy",
    "RecoveryManager",
    "DegradationLevel",
    "DegradationReason",
    "DegradationRecoveryStrategy",
    "DegradationState",
    "DegradationMetrics",
    "DegradationThresholds",
    "DegradationConfig",
    "FallbackResponse",
    "create_graceful_provider",
    "create_fallback_chain",
    # Observability (Phase 9)
    "MetricsCollector",
    "StructuredLogger",
    "AlertManager",
    "HealthChecker",
    "SLOMonitor",
    "ObservabilityContext",
    "ObservableVisionProvider",
    "ObservabilityMetricType",
    "ObservabilityLogLevel",
    "ObservabilityAlertSeverity",
    "AlertStatus",
    "ObservabilityHealthStatus",
    "ObservabilityMetricValue",
    "HistogramBucket",
    "ObservabilityHistogramValue",
    "LogEntry",
    "Alert",
    "AlertRule",
    "HealthCheck",
    "SLI",
    "SLO",
    "create_observable_provider",
    # Deployment (Phase 9)
    "DeploymentManager",
    "DeploymentVisionProvider",
    "TrafficRouter",
    "BlueGreenDeployment",
    "CanaryRelease",
    "RollingUpdate",
    "DeploymentStrategy",
    "DeploymentPhase",
    "EnvironmentType",
    "TrafficSplitMethod",
    "DeploymentVersion",
    "DeploymentConfig",
    "DeploymentMetricsData",
    "DeploymentState",
    "create_blue_green_provider",
    "create_canary_provider",
    # Multi-Tenancy (Phase 9)
    "TenantManager",
    "MultiTenantVisionProvider",
    "TenantQuotaManager",
    "UsageTracker",
    "TenantContext",
    "TenantStore",
    "InMemoryTenantStore",
    "TenantStatus",
    "TenantTier",
    "IsolationLevel",
    "QuotaType",
    "ResourceQuota",
    "TenantConfig",
    "Tenant",
    "TenantUsage",
    "create_multi_tenant_provider",
    # Compliance (Phase 9)
    "ComplianceManager",
    "ComplianceVisionProvider",
    "ComplianceAuditLogger",
    "PIIDetector",
    "DataRetentionManager",
    "ComplianceAuditEventType",
    "ComplianceAuditSeverity",
    "ComplianceStandard",
    "DataClassification",
    "ComplianceRetentionPolicy",
    "AuditEvent",
    "DataRetentionConfig",
    "ComplianceRequirement",
    "PIIDetectionResult",
    "create_compliant_provider",
    # Chaos Engineering (Phase 9)
    "ChaosManager",
    "ChaosVisionProvider",
    "FaultInjector",
    "LatencyInjector",
    "ErrorInjector",
    "ChaosExperiment",
    "FaultType",
    "ChaosExperimentStatus",
    "TargetType",
    "InjectionStrategy",
    "FaultConfig",
    "ChaosExperimentConfig",
    "ChaosExperimentResult",
    "create_chaos_provider",
    "create_experiment",
    # Event Sourcing (Phase 10)
    "EventStore",
    "InMemoryEventStore",
    "SnapshotStore",
    "InMemorySnapshotStore",
    "Aggregate",
    "VisionRequestAggregate",
    "Projection",
    "RequestCountProjection",
    "LatencyProjection",
    "Command",
    "Query",
    "CommandHandler",
    "QueryHandler",
    "GetRequestStatsQuery",
    "GetRequestStatsHandler",
    "EventSourcedVisionProvider",
    "Event",
    "Snapshot",
    "AggregateRoot",
    "EventType",
    "AggregateType",
    "create_event_sourced_provider",
    # Plugin System (Phase 10)
    "PluginManager",
    "PluginRegistry",
    "PluginPipeline",
    "PluggableVisionProvider",
    "Plugin",
    "VisionProviderPlugin",
    "PreprocessorPlugin",
    "PostprocessorPlugin",
    "MiddlewarePlugin",
    "HookManager",
    "PluginDiscovery",
    "PluginSandbox",
    "PluginState",
    "PluginType",
    "HookPriority",
    "PluginCapability",
    "PluginMetadata",
    "PluginInstance",
    "HookRegistration",
    "PluginEvent",
    "create_plugin_manager",
    "create_plugin_pipeline",
    # API Gateway (Phase 10)
    "ApiGateway",
    "VisionApiGateway",
    "Router",
    "GatewayLoadBalancer",
    "ApiVersionManager",
    "ApiAggregator",
    "GatewayMiddleware",
    "GatewayLoggingMiddleware",
    "CorsMiddleware",
    "CompressionMiddleware",
    "GatewayRequestTransformer",
    "GatewayResponseTransformer",
    "HeaderInjectionTransformer",
    "PathRewriteTransformer",
    "JsonResponseTransformer",
    "HttpMethod",
    "LoadBalanceStrategy",
    "ProtocolType",
    "ResponseStatus",
    "GatewayRequest",
    "GatewayResponse",
    "RouteConfig",
    "GatewayServiceEndpoint",
    "ApiVersion",
    "create_api_gateway",
    "create_vision_gateway",
    "create_gateway_load_balancer",
    # Distributed Lock (Phase 10)
    "LockManager",
    "DistributedLock",
    "InMemoryLock",
    "ReentrantLock",
    "ReadWriteLock",
    "DistributedSemaphore",
    "FencingTokenManager",
    "LockedVisionProvider",
    "LockType",
    "LockState",
    "LockAcquisitionResult",
    "LockInfo",
    "LockRequest",
    "LockResult",
    "DeadlockInfo",
    "create_lock_manager",
    "create_reentrant_lock",
    "create_read_write_lock",
    "create_semaphore",
    # Workflow Engine (Phase 10)
    "WorkflowEngine",
    "WorkflowBuilder",
    "WorkflowVisionProvider",
    "TaskHandler",
    "VisionAnalysisTask",
    "ConditionalTask",
    "ParallelTask",
    "SequentialTask",
    "ImagePreprocessTask",
    "ImageAnalysisTask",
    "ResultAggregationTask",
    "StateMachine",
    "WorkflowStatus",
    "TaskStatus",
    "TriggerType",
    "WorkflowRetryPolicy",
    "TaskDefinition",
    "WorkflowDefinition",
    "TaskExecution",
    "WorkflowExecution",
    "WorkflowEvent",
    "StateTransition",
    "create_workflow_engine",
    "create_workflow_builder",
    "create_vision_workflow",
    # Encryption (Phase 11)
    "EncryptionService",
    "EncryptedVisionProvider",
    "KeyManager",
    "KeyStore",
    "InMemoryKeyStore",
    "Encryptor",
    "SimpleAESEncryptor",
    "Hasher",
    "HMACAuthenticator",
    "SecureStorage",
    "EncryptionAlgorithm",
    "KeyType",
    "KeyStatus",
    "HashAlgorithm",
    "KeyMetadata",
    "EncryptedData",
    "SecureValue",
    "create_encryption_service",
    "create_encrypted_provider",
    # Audit Logging (Phase 11)
    "AuditLogger",
    "AuditedVisionProvider",
    "AuditStore",
    "InMemoryAuditStore",
    "ComplianceTracker",
    "AuditTrail",
    "AuditEventType",
    "AuditSeverity",
    "ComplianceFramework",
    "AuditActor",
    "AuditResource",
    "AuditEvent",
    "ComplianceRequirement",
    "create_audit_logger",
    "create_audited_provider",
    "create_compliance_tracker",
    # Data Pipeline (Phase 11)
    "Pipeline",
    "PipelineBuilder",
    "VisionPipelineProvider",
    "ETLPipeline",
    "BatchProcessor",
    "DataSource",
    "DataSink",
    "InMemoryDataSource",
    "InMemoryDataSink",
    "Transformer",
    "MapTransformer",
    "FilterTransformer",
    "FieldExtractTransformer",
    "EnrichTransformer",
    "PipelineStageType",
    "PipelineStatus",
    "DataFormat",
    "DataRecord",
    "BatchResult",
    "PipelineStage",
    "PipelineConfig",
    "create_pipeline",
    "create_etl_pipeline",
    "create_batch_processor",
    # Stream Processing (Phase 11)
    "Stream",
    "StreamBuilder",
    "StreamingVisionProvider",
    "Window",
    "TumblingWindow",
    "SlidingWindow",
    "SessionWindow",
    "CountWindow",
    "WindowedStream",
    "StreamOperator",
    "MapOperator",
    "FilterOperator",
    "FlatMapOperator",
    "KeyByOperator",
    "Aggregator",
    "SumAggregator",
    "CountAggregator",
    "AverageAggregator",
    "MinAggregator",
    "MaxAggregator",
    "WindowType",
    "TriggerType",
    "StreamState",
    "StreamEvent",
    "WindowResult",
    "create_stream",
    "create_streaming_provider",
    # Data Validation (Phase 11)
    "Schema",
    "SchemaBuilder",
    "ValidatedVisionProvider",
    "Validator",
    "TypeValidator",
    "RequiredValidator",
    "RangeValidator",
    "LengthValidator",
    "PatternValidator",
    "EnumValidator",
    "CustomValidator",
    "CompositeValidator",
    "DataQualityChecker",
    "ValidationSeverity",
    "ValidationStatus",
    "DataType",
    "ValidationError",
    "ValidationResult",
    "FieldSchema",
    "create_schema",
    "create_validator",
    "create_quality_checker",
    "create_validated_provider",
    # ML Integration (Phase 12)
    "ModelRegistry",
    "MLVisionProvider",
    "InferenceEngine",
    "InferencePipeline",
    "ModelStore",
    "InMemoryModelStore",
    "FeatureExtractor",
    "ImageFeatureExtractor",
    "CompositeFeatureExtractor",
    "MLModel",
    "SimpleClassifier",
    "EnsembleModel",
    "ModelType",
    "ModelStatus",
    "InferenceMode",
    "FeatureType",
    "ModelMetadata",
    "ModelVersion",
    "MLFeature",
    "FeatureVector",
    "InferenceRequest",
    "InferenceResult",
    "MLPipelineStage",
    "MLPipelineConfig",
    "create_model_registry",
    "create_inference_engine",
    "create_ml_provider",
    "create_feature_extractor",
    "create_simple_classifier",
    "create_ensemble_model",
    # Recommendations (Phase 12)
    "RecommendationEngine",
    "RecommendationVisionProvider",
    "SimilarityCalculator",
    "ItemStore",
    "InMemoryItemStore",
    "InteractionStore",
    "InMemoryInteractionStore",
    "RecommendationStrategy",
    "PopularityStrategy",
    "ContentBasedStrategy",
    "CollaborativeStrategy",
    "RecommendationType",
    "SimilarityMetric",
    "InteractionType",
    "Item",
    "RecommendationUser",
    "Interaction",
    "Recommendation",
    "RecommendationRequest",
    "RecommendationResult",
    "SimilarityResult",
    "create_recommendation_engine",
    "create_recommendation_provider",
    "create_similarity_calculator",
    "create_item",
    "create_interaction",
    # Anomaly Detection (Phase 12)
    "AnomalyDetectionEngine",
    "AnomalyDetectionVisionProvider",
    "AnomalyAlertManager",
    "AnomalyDetector",
    "ZScoreDetector",
    "IQRDetector",
    "ThresholdDetector",
    "MovingAverageDetector",
    "AnomalyType",
    "DetectionMethod",
    "AnomalySeverity",
    "AnomalyAlertStatus",
    "DataPoint",
    "Anomaly",
    "AnomalyAlert",
    "AnomalyThreshold",
    "DetectionConfig",
    "DetectionResult",
    "create_anomaly_engine",
    "create_anomaly_provider",
    "create_zscore_detector",
    "create_iqr_detector",
    "create_threshold_detector",
    "create_moving_average_detector",
    "create_alert_manager",
    "create_threshold",
    # Reporting (Phase 12)
    "ReportGenerator",
    "ReportBuilder",
    "ReportingVisionProvider",
    "DashboardManager",
    "ReportScheduler",
    "ReportFormatter",
    "JSONFormatter",
    "MarkdownFormatter",
    "CSVFormatter",
    "HTMLFormatter",
    "ReportType",
    "ReportFormat",
    "ChartType",
    "ReportStatus",
    "ScheduleFrequency",
    "DataSeries",
    "ChartConfig",
    "ReportSection",
    "ReportConfig",
    "Report",
    "DashboardWidget",
    "Dashboard",
    "ScheduledReport",
    "ExportResult",
    "create_report_generator",
    "create_report_builder",
    "create_dashboard_manager",
    "create_report_scheduler",
    "create_reporting_provider",
    "create_chart_config",
    "create_data_series",
    "create_dashboard_widget",
    # Message Queue (Phase 13)
    "MessageQueue",
    "MessageBroker",
    "MessageQueueVisionProvider",
    "Publisher",
    "Subscriber",
    "DeadLetterQueue",
    "Message",
    "MessageStatus",
    "DeliveryMode",
    "QueueType",
    "AckMode",
    "MessageBatch",
    "PublishResult",
    "ConsumeResult",
    "QueueConfig",
    "MessageQueueStats",
    "Subscription",
    "create_message_queue",
    "create_message_broker",
    "create_mq_provider",
    "create_message",
    "create_dead_letter_queue",
    # Distributed Cache (Phase 13)
    "DistributedCache",
    "DistributedCacheVisionProvider",
    "CacheManager",
    "CacheShard",
    "ConsistentHashRing",
    "CacheNode",
    "CacheStrategy",
    "ConsistencyLevel",
    "InvalidationStrategy",
    "CacheNodeStatus",
    "CacheEntry",
    "DistributedCacheStats",
    "CacheConfig",
    "ShardInfo",
    "create_distributed_cache",
    "create_cache_manager",
    "create_dcache_provider",
    "create_cache_config",
    "create_consistent_hash_ring",
    # Saga Pattern (Phase 13)
    "SagaOrchestrator",
    "SagaVisionProvider",
    "SagaDefinition",
    "SagaBuilder",
    "CompensationManager",
    "TransactionCoordinator",
    "TransactionParticipant",
    "SimpleParticipant",
    "ChoreographySaga",
    "SagaStep",
    "SagaContext",
    "SagaExecution",
    "SagaStatus",
    "StepStatus",
    "create_saga_orchestrator",
    "create_saga_builder",
    "create_compensation_manager",
    "create_transaction_coordinator",
    "create_choreography_saga",
    "create_saga_provider",
    # Event Bus (Phase 13)
    "EventBus",
    "EventDrivenVisionProvider",
    "EventRouter",
    "EventBusStore",
    "EventAggregator",
    "CommandBus",
    "QueryBus",
    "EventHandler",
    "FunctionEventHandler",
    "EventBusEvent",
    "VisionEvent",
    "ImageAnalyzedEvent",
    "AnalysisFailedEvent",
    "EventEnvelope",
    "EventPriority",
    "EventStatus",
    "create_event_bus",
    "create_event_router",
    "create_event_bus_store",
    "create_event_aggregator",
    "create_command_bus",
    "create_query_bus",
    "create_event_provider",
    # Access Control (Phase 14 - merged with Phase 19)
    "RoleManager",
    "AccessControlManager",
    "AccessControlVisionProvider",
    "Role",
    "AccessPermission",
    "AccessUser",
    "AccessDecision",
    "AccessRequest",
    "AccessResult",
    "Resource",
    "ResourceType",
    "create_access_manager",
    "create_acl_provider",
    "create_role",
    # Data Masking (Phase 14)
    "MaskingEngine",
    "DataMaskingVisionProvider",
    "PIIDetector",
    "RegexPIIDetector",
    "HeuristicPIIDetector",
    "DataMasker",
    "RedactionMasker",
    "PartialMasker",
    "HashMasker",
    "TokenizeMasker",
    "PseudonymizeMasker",
    "PIIType",
    "MaskingStrategy",
    "SensitivityLevel",
    "PIIMatch",
    "MaskingRule",
    "MaskingResult",
    "DetectionReport",
    "create_masking_engine",
    "create_masking_provider",
    "create_regex_detector",
    "create_heuristic_detector",
    "create_masking_rule",
    "create_redaction_masker",
    "create_partial_masker",
    "create_hash_masker",
    "create_tokenize_masker",
    "create_pseudonymize_masker",
    # Security Audit (Phase 14)
    "SecurityAuditManager",
    "SecurityAuditVisionProvider",
    "ThreatDetector",
    "BruteForceDetector",
    "SecurityAnomalyDetector",
    "IPReputationDetector",
    "SecurityAuditLogger",
    "SecurityAlertManager",
    "SecurityEventType",
    "SecuritySeverityLevel",
    "ThreatLevel",
    "SecurityAlertStatus",
    "SecurityEvent",
    "SecurityAlert",
    "ThreatIndicator",
    "AuditPolicy",
    "SecurityMetrics",
    "create_security_audit_manager",
    "create_security_audit_provider",
    "create_brute_force_detector",
    "create_security_anomaly_detector",
    "create_ip_reputation_detector",
    "create_security_audit_logger",
    "create_security_alert_manager",
    "create_security_event",
    "create_audit_policy",
    # Key Management (Phase 14)
    "Phase14KeyManager",
    "KeyManagedVisionProvider",
    "KeyGenerator",
    "Phase14KeyStore",
    "Phase14InMemoryKeyStore",
    "EncryptedKeyStore",
    "SecretsVault",
    "KeyRotationPolicy",
    "Phase14KeyType",
    "Phase14KeyStatus",
    "KeyAlgorithm",
    "SecretType",
    "CryptoKey",
    "Secret",
    "KeyAuditEntry",
    "create_key_manager",
    "create_key_managed_provider",
    "create_key_generator",
    "create_in_memory_key_store",
    "create_encrypted_key_store",
    "create_secrets_vault",
    "create_rotation_policy",
    "create_crypto_key",
    # Privacy Compliance (Phase 14)
    "PrivacyComplianceManager",
    "PrivacyComplianceVisionProvider",
    "ConsentManager",
    "ConsentStore",
    "InMemoryConsentStore",
    "DataSubjectRequestHandler",
    "PrivacyRetentionManager",
    "ProcessingActivityLog",
    "PrivacyRegulation",
    "ConsentType",
    "LegalBasis",
    "DataSubjectRight",
    "PrivacyRequestStatus",
    "Consent",
    "DataSubjectRequest",
    "DataRetentionPolicy",
    "ProcessingActivity",
    "PrivacyImpactAssessment",
    "create_consent_manager",
    "create_consent_store",
    "create_request_handler",
    "create_privacy_retention_manager",
    "create_activity_log",
    "create_privacy_compliance_manager",
    "create_compliance_provider",
    # Predictive Analytics (Phase 15)
    "PredictiveEngine",
    "PredictiveVisionProvider",
    "DemandPredictor",
    "AnomalyPredictor",
    "TimeSeriesStore",
    "TrendAnalyzer",
    "MovingAverageModel",
    "ExponentialSmoothingModel",
    "PredictionType",
    "PredictionModelType",
    "ForecastHorizon",
    "TrendDirection",
    "DataPoint",
    "PredictionResult",
    "TrendAnalysis",
    "ForecastResult",
    "PredictionModelMetrics",
    "create_predictive_engine",
    "create_predictive_provider",
    "create_demand_predictor",
    "create_anomaly_predictor",
    # Intelligent Routing (Phase 15)
    "IntelligentRouter",
    "RoutedVisionProvider",
    "LoadBalancer",
    "AdaptiveRouter",
    "ContentAnalyzer",
    "CapabilityMatchRule",
    "LatencyConstraintRule",
    "CostConstraintRule",
    "RoutingStrategy",
    "ProviderCapability",
    "RequestPriority",
    "ProviderStats",
    "RoutingDecision",
    "RoutingContext",
    "RoutingProviderConfig",
    "create_intelligent_router",
    "create_routed_provider",
    "create_provider_config",
    "create_routing_context",
    # Auto Scaling (Phase 15)
    "AutoScaler",
    "AutoScaledVisionProvider",
    "MetricsCollector",
    "ScalingPredictor",
    "ReactiveScaler",
    "PredictiveScaler",
    "ScheduledScaler",
    "ScalingDirection",
    "ScalingPolicy",
    "ScalingResourceType",
    "ScalingState",
    "ScalingConfig",
    "ScalingMetrics",
    "ScalingDecision",
    "ScalingEvent",
    "CapacityPlan",
    "create_scaling_config",
    "create_auto_scaler",
    "create_auto_scaled_provider",
    "create_capacity_plan",
    # Self Healing (Phase 15)
    "SelfHealingEngine",
    "SelfHealingVisionProvider",
    "HealthMonitor",
    "IssueDetector",
    "RecoveryPlanner",
    "RecoveryExecutor",
    "HealthStatus",
    "IssueType",
    "RecoveryAction",
    "RecoveryStatus",
    "HealthCheck",
    "Issue",
    "RecoveryPlan",
    "RecoveryResult",
    "HealingEvent",
    "create_health_monitor",
    "create_self_healing_engine",
    "create_self_healing_provider",
    "create_health_check",
    # Knowledge Base (Phase 15)
    "KnowledgeBase",
    "KnowledgeEnhancedVisionProvider",
    "KnowledgeGraph",
    "SemanticIndex",
    "KnowledgeStore",
    "EntityType",
    "RelationType",
    "SearchStrategy",
    "Entity",
    "Relationship",
    "KnowledgeSearchResult",
    "KnowledgeQueryResult",
    "KnowledgeEntry",
    "create_knowledge_graph",
    "create_knowledge_base",
    "create_knowledge_provider",
    "create_entity",
    "create_relationship",
    # Plugin Manager (Phase 16)
    "PluginManager",
    "PluginVisionProvider",
    "PluginRegistry",
    "HookExecutor",
    "PluginLoader",
    "DependencyContainer",
    "PluginType",
    "PluginState",
    "HookType",
    "PluginMetadata",
    "PluginInfo",
    "HookResult",
    "Plugin",
    "VisionPlugin",
    "ProviderPlugin",
    "FilterPlugin",
    "TransformerPlugin",
    "create_plugin_manager",
    "create_plugin_provider",
    "create_dependency_container",
    "create_plugin_metadata",
    # API Versioning (Phase 16)
    "ApiVersionManager",
    "VersionedVisionProvider",
    "SemanticVersion",
    "VersionRegistry",
    "DeprecationManager",
    "VersionNegotiator",
    "VersionRouter",
    "VersionStatus",
    "CompatibilityLevel",
    "VersionChangeType",
    "VersionInfo",
    "ApiChange",
    "VersionDeprecationWarning",
    "create_version_manager",
    "create_versioned_provider",
    "create_semantic_version",
    "create_version_info",
    # SDK Generator (Phase 16)
    "SDKGenerator",
    "SDKGeneratorVisionProvider",
    "PythonGenerator",
    "TypeScriptGenerator",
    "OpenAPIGenerator",
    "GraphQLSchemaGenerator",
    "APIDefinitionBuilder",
    "SDKLanguage",
    "SpecFormat",
    "HTTPMethod",
    "ParameterLocation",
    "SDKDataType",
    "SchemaProperty",
    "SchemaDefinition",
    "ParameterDefinition",
    "ResponseDefinition",
    "EndpointDefinition",
    "APIDefinition",
    "GeneratedFile",
    "SDKConfig",
    "SDKGenerationResult",
    "create_sdk_generator",
    "create_api_definition_builder",
    "create_sdk_generator_provider",
    "create_python_generator",
    "create_typescript_generator",
    "create_openapi_generator",
    "create_graphql_generator",
    # Integration Hub (Phase 16)
    "IntegrationHub",
    "IntegrationHubVisionProvider",
    "Connector",
    "RESTConnector",
    "WebSocketConnector",
    "IntegrationWebhookManager",
    "IntegrationRateLimiter",
    "DataTransformer",
    "ConnectorType",
    "AuthenticationType",
    "ConnectorStatus",
    "WebhookEventType",
    "DataFormat",
    "AuthCredentials",
    "IntegrationRateLimitConfig",
    "ConnectorConfig",
    "IntegrationWebhookConfig",
    "WebhookPayload",
    "IntegrationHealth",
    "DataMapping",
    "TransformResult",
    "create_integration_hub",
    "create_rest_connector",
    "create_websocket_connector",
    "create_integration_webhook_manager",
    "create_integration_rate_limiter",
    "create_data_transformer",
    "create_integration_hub_provider",
    # Documentation Generator (Phase 16)
    "DocumentationGenerator",
    "DocumentedVisionProvider",
    "MarkdownGenerator",
    "HTMLGenerator",
    "CodeExtractor",
    "DocstringParser",
    "DocFormat",
    "DocSection",
    "ChangeType",
    "DocParameterType",
    "ParameterDoc",
    "ReturnDoc",
    "ExceptionDoc",
    "MethodDoc",
    "ClassDoc",
    "ModuleDoc",
    "ChangeLogEntry",
    "ChangeLog",
    "DocConfig",
    "GeneratedDoc",
    "DocGenerationResult",
    "create_documentation_generator",
    "create_markdown_generator",
    "create_html_generator",
    "create_code_extractor",
    "create_docstring_parser",
    "create_documented_provider",
    # Metrics Dashboard (Phase 17)
    "MetricCollector",
    "MetricsDashboardManager",
    "MetricStreamer",
    "CustomMetricBuilder",
    "MetricsDashboardVisionProvider",
    "DashboardMetricType",
    "AggregationType",
    "WidgetType",
    "TimeRange",
    "RefreshInterval",
    "MetricDefinition",
    "MetricDataPoint",
    "TimeSeriesData",
    "MetricsDashboardWidget",
    "MetricsDashboardConfig",
    "create_metric_collector",
    "create_metrics_dashboard_manager",
    "create_metric_streamer",
    "create_custom_metric_builder",
    "create_metrics_dashboard_provider",
    # Alert Manager (Phase 17)
    "Phase17AlertManager",
    "AlertEvaluator",
    "AlertManagerVisionProvider",
    "Phase17AlertSeverity",
    "AlertState",
    "NotificationChannel",
    "ComparisonOperator",
    "EscalationAction",
    "Phase17AlertRule",
    "AlertCondition",
    "AlertInstance",
    "NotificationConfig",
    "EscalationPolicy",
    "SilenceRule",
    "InhibitionRule",
    "create_phase17_alert_manager",
    "create_phase17_alert_rule",
    "create_notification_channel",
    "create_silence",
    "create_escalation_policy",
    "create_alert_manager_provider",
    # Log Aggregator (Phase 17)
    "LogAggregator",
    "AggregatorLogStore",
    "LogCorrelator",
    "PatternDetector",
    "LogAggregatorVisionProvider",
    "AggregatorLogLevel",
    "LogSource",
    "ParserType",
    "AggregationMode",
    "AggregatorLogEntry",
    "LogFilter",
    "CorrelationResult",
    "LogPattern",
    "LogStats",
    "RetentionConfig",
    "create_log_aggregator",
    "create_json_parser",
    "create_regex_parser",
    "create_log_retention_policy",
    "create_log_aggregator_provider",
    # APM Integration (Phase 17)
    "APMManager",
    "SpanTracker",
    "TransactionTracker",
    "PerformanceAnalyzer",
    "ErrorTracker",
    "DependencyTracker",
    "APMVisionProvider",
    "TransactionType",
    "APMSpanKind",
    "APMSpanStatus",
    "APMProvider",
    "ProfileType",
    "Transaction",
    "APMSpan",
    "ErrorRecord",
    "DependencyRecord",
    "APMPerformanceMetrics",
    "APMConfig",
    "create_apm_manager",
    "create_apm_config",
    "create_apm_provider",
    # SLA Monitor (Phase 17)
    "SLAMonitor",
    "SLATracker",
    "UptimeTracker",
    "SLAReporter",
    "SLAMonitorVisionProvider",
    "SLAType",
    "SLAStatus",
    "UptimeStatus",
    "ReportPeriod",
    "CheckType",
    "SLADefinition",
    "SLAMeasurement",
    "UptimeCheck",
    "UptimeIncident",
    "SLAReport",
    "create_sla_monitor",
    "create_sla_definition",
    "create_uptime_check",
    "create_sla_monitor_provider",
    # AutoML Engine (Phase 18)
    "AutoMLEngine",
    "HyperparameterOptimizer",
    "RandomSearchOptimizer",
    "BayesianOptimizer",
    "ModelSelector",
    "NeuralArchitectureSearch",
    "AutoMLFeatureSelector",
    "EnsembleBuilder",
    "AutoMLVisionProvider",
    "SearchStrategy",
    "OptimizationObjective",
    "AutoMLModelType",
    "AutoMLTaskType",
    "TrialStatus",
    "EarlyStoppingStrategy",
    "HyperparameterSpace",
    "TrialResult",
    "SearchConfig",
    "ModelCandidate",
    "EnsembleConfig",
    "AutoMLResult",
    "create_automl_engine",
    "create_search_config",
    "create_hyperparameter_space",
    "create_model_selector",
    "create_nas",
    "create_automl_feature_selector",
    "create_ensemble_builder",
    "create_automl_provider",
    # Feature Store (Phase 18)
    "FeatureRegistry",
    "FeatureStore",
    "FeatureComputer",
    "FeatureStoreValidator",
    "FeatureStatisticsComputer",
    "FeatureStoreVisionProvider",
    "FeatureType",
    "FeatureStatus",
    "ComputationMode",
    "TransformationType",
    "AggregationWindow",
    "DataQualityCheck",
    "FeatureDefinition",
    "FeatureValue",
    "FeatureGroup",
    "FeatureTransformation",
    "FeatureLineage",
    "FeatureStatistics",
    "FeatureQualityReport",
    "create_feature_registry",
    "create_feature_store",
    "create_feature_definition",
    "create_feature_group",
    "create_feature_transformation",
    "create_feature_computer",
    "create_feature_validator",
    "create_feature_store_provider",
    # Model Registry (Phase 18)
    "ModelRegistry",
    "ModelDeployer",
    "ABTestManager",
    "ApprovalWorkflow",
    "ModelRegistryValidator",
    "ModelRegistryVisionProvider",
    "ModelStage",
    "ModelRegistryStatus",
    "DeploymentStrategy",
    "ServingFormat",
    "ApprovalStatus",
    "ModelMetricType",
    "ModelVersion",
    "ModelMetadata",
    "ModelLineage",
    "DeploymentConfig",
    "Deployment",
    "ABTestConfig",
    "ABTestResult",
    "ApprovalRequest",
    "create_model_registry",
    "create_model_version",
    "create_model_metadata",
    "create_deployment_config",
    "create_ab_test_config",
    "create_model_deployer",
    "create_ab_test_manager",
    "create_approval_workflow",
    "create_model_registry_provider",
    # Pipeline Orchestrator (Phase 18)
    "PipelineOrchestrator",
    "DAGBuilder",
    "TaskExecutor",
    "PipelineScheduler",
    "PipelineTemplate",
    "PipelineOrchestratorVisionProvider",
    "PipelineTaskStatus",
    "PipelineStatus",
    "TriggerType",
    "RetryPolicy",
    "ExecutionMode",
    "ResourceType",
    "TaskDefinition",
    "TaskInstance",
    "PipelineDefinition",
    "PipelineRun",
    "DAGNode",
    "ScheduleConfig",
    "ResourceRequirements",
    "create_pipeline_orchestrator",
    "create_pipeline_definition",
    "create_task_definition",
    "create_dag_builder",
    "create_task_executor",
    "create_pipeline_scheduler",
    "create_schedule_config",
    "create_pipeline_template",
    "create_pipeline_orchestrator_provider",
    # Experiment Tracker (Phase 18)
    "ExperimentTracker",
    "ExperimentStore",
    "RunContext",
    "MetricAggregator",
    "HyperparameterAnalyzer",
    "ExperimentTrackerVisionProvider",
    "RunStatus",
    "MetricGoal",
    "ArtifactType",
    "ComparisonMode",
    "TagType",
    "Experiment",
    "ExperimentRun",
    "ExperimentParameter",
    "ExperimentMetric",
    "MetricHistory",
    "ExperimentArtifact",
    "ComparisonResult",
    "SearchQuery",
    "create_experiment_tracker",
    "create_experiment",
    "create_experiment_run",
    "create_experiment_metric",
    "create_experiment_parameter",
    "create_experiment_artifact",
    "create_search_query",
    "create_metric_aggregator",
    "create_hyperparameter_analyzer",
    "create_experiment_tracker_provider",
    # Security Scanner (Phase 19)
    "SecurityScanner",
    "CodeScanner",
    "DependencyScanner",
    "ThreatDetector",
    "RiskAssessor",
    "SecurityScannerVisionProvider",
    "VulnerabilitySeverity",
    "ScanType",
    "ThreatCategory",
    "ScanStatus",
    "RemediationPriority",
    "SecurityRiskLevel",
    "Vulnerability",
    "ScanConfig",
    "ScanResult",
    "ThreatIndicator",
    "RiskAssessment",
    "SecurityPolicy",
    "create_security_scanner",
    "create_scan_config",
    "create_vulnerability",
    "create_threat_indicator",
    "create_security_policy",
    "create_code_scanner",
    "create_dependency_scanner",
    "create_threat_detector",
    "create_risk_assessor",
    "create_security_scanner_provider",
    # Access Control (Phase 19)
    "AccessController",
    "UserManager",
    "RoleManager",
    "SessionManager",
    "APIKeyManager",
    "AccessControlVisionProvider",
    "Permission",
    "RoleType",
    "AuthMethod",
    "SessionStatus",
    "AccessDecision",
    "ACLResourceType",
    "ACLUser",
    "ACLRole",
    "ACLResource",
    "ACLSession",
    "APIKey",
    "AccessRequest",
    "AccessResult",
    "Tenant",
    "create_access_controller",
    "create_acl_user",
    "create_acl_role",
    "create_acl_resource",
    "create_access_request",
    "create_user_manager",
    "create_role_manager",
    "create_session_manager",
    "create_api_key_manager",
    "create_access_control_provider",
    # Audit Logger (Phase 19)
    "AuditLogger",
    "ComplianceAuditLogger",
    "MemoryAuditStore",
    "AuditLoggerVisionProvider",
    "AuditEventType",
    "AuditSeverity",
    "AuditCategory",
    "LogDestination",
    "RetentionPeriod",
    "AuditEvent",
    "AuditQuery",
    "AuditSummary",
    "AuditPolicy",
    "AuditAlert",
    "LogIntegrity",
    "create_audit_logger",
    "create_compliance_audit_logger",
    "create_audit_event",
    "create_audit_query",
    "create_audit_policy",
    "create_audit_alert",
    "create_memory_audit_store",
    "create_audit_logger_provider",
    # Encryption Manager (Phase 19)
    "EncryptionManager",
    "KeyGenerator",
    "Encryptor",
    "KeyRotationManager",
    "MemoryKeyStore",
    "EncryptionManagerVisionProvider",
    "EncryptionAlgorithm",
    "KeyType",
    "KeyStatus",
    "KeyPurpose",
    "HashAlgorithm",
    "EncryptionKey",
    "EncryptedData",
    "KeyPolicy",
    "Certificate",
    "KeyRotationEvent",
    "create_encryption_manager",
    "create_memory_key_store",
    "create_key_generator",
    "create_encryptor",
    "create_key_policy",
    "create_encryption_manager_provider",
    # Compliance Checker (Phase 19)
    "ComplianceChecker",
    "ControlRegistry",
    "ControlAssessor",
    "PolicyEngine",
    "ComplianceReporter",
    "DataInventory",
    "ComplianceCheckerVisionProvider",
    "ComplianceFramework",
    "ComplianceStatus",
    "ControlCategory",
    "ComplianceRiskLevel",
    "DataClassification",
    "PolicyType",
    "ComplianceControl",
    "ControlAssessment",
    "CompliancePolicy",
    "PolicyViolation",
    "ComplianceReport",
    "DataInventoryItem",
    "PrivacyImpactAssessment",
    "create_compliance_checker",
    "create_compliance_control",
    "create_compliance_policy",
    "create_data_inventory_item",
    "create_privacy_impact_assessment",
    "create_control_registry",
    "create_policy_engine",
    "create_data_inventory",
    "create_compliance_checker_provider",
    # Webhook Handler (Phase 20)
    "WebhookManagerP20",
    "WebhookRegistryP20",
    "WebhookDeliveryService",
    "WebhookRateLimiter",
    "WebhookSignature",
    "WebhookVisionProvider",
    "WebhookEventTypeP20",
    "WebhookStatus",
    "DeliveryStatus",
    "SignatureAlgorithm",
    "WebhookConfigP20",
    "WebhookRegistration",
    "WebhookEvent",
    "DeliveryAttempt",
    "DeliveryRecord",
    "create_webhook_config_p20",
    "create_webhook_manager_p20",
    "create_webhook_event",
    # Observability Hub (Phase 21)
    "ObservabilityHub",
    "ObservableVisionProvider",
    "MetricsCollector",
    "TraceManager",
    "HealthMonitor",
    "AlertManagerP21",
    "SLOTracker",
    "AnomalyDetector",
    "MetricType",
    "HealthStatusP21",
    "AlertSeverityP21",
    "AlertState",
    "TraceStatus",
    "SLOStatus",
    "AnomalyType",
    "MetricPoint",
    "MetricSeries",
    "SpanContext",
    "Span",
    "HealthCheckP21",
    "AlertP21",
    "SLODefinition",
    "SLOResult",
    "Anomaly",
    "ObservabilityConfig",
    "create_observability_hub",
    "create_metrics_collector",
    "create_trace_manager",
    "create_health_monitor",
    "create_alert_manager_p21",
    "create_slo_definition",
    "create_observable_provider",
    # Security Governance Hub (Phase 22)
    "SecurityGovernanceHub",
    "SecureVisionProvider",
    "PolicyEngine",
    "DataClassificationManager",
    "KeyManager",
    "SecretManager",
    "ThreatIntelManager",
    "SecurityEventCorrelator",
    "SecurityPostureAssessor",
    "DataClassification",
    "PolicyTypeP22",
    "PolicyStatusP22",
    "PolicyAction",
    "EncryptionAlgorithm",
    "KeyStatus",
    "SecretType",
    "ThreatLevel",
    "SecurityEventType",
    "PostureStatus",
    "SecurityPolicy",
    "PolicyEvaluation",
    "DataClassificationRule",
    "EncryptionKey",
    "Secret",
    "ThreatIndicator",
    "SecurityEvent",
    "SecurityPosture",
    "GovernanceConfig",
    "create_governance_config",
    "create_security_governance_hub",
    "create_security_policy",
    "create_classification_rule",
    "create_threat_indicator",
    "create_secure_provider",
    # Intelligent Automation Hub (Phase 23)
    "IntelligentAutomationHub",
    "AutomatedVisionProvider",
    "DecisionEngine",
    "SelfTuner",
    "IntelligentScheduler",
    "LoadManager",
    "PerformancePredictor",
    "AutoRemediation",
    "PatternLearner",
    "DecisionType",
    "DecisionConfidence",
    "TuningStrategy",
    "TuningStatus",
    "SchedulerPriority",
    "TaskStateP23",
    "LoadLevel",
    "RemediationAction",
    "PredictionType",
    "LearningMode",
    "Decision",
    "DecisionRule",
    "TuningParameter",
    "TuningSession",
    "ScheduledTask",
    "ResourcePool",
    "LoadMetrics",
    "Remediation",
    "Prediction",
    "LearningPattern",
    "AutomationConfig",
    "create_automation_config",
    "create_intelligent_automation_hub",
    "create_decision_rule",
    "create_load_metrics",
    "create_automated_provider",
    # Data Lifecycle Hub (Phase 24)
    "DataLifecycleHub",
    "ManagedVisionProvider",
    "VersionManager",
    "LineageTracker",
    "QualityManager",
    "RetentionManager",
    "DataCatalog",
    "TransformationTracker",
    "DataState",
    "VersionType",
    "LineageRelation",
    "QualityDimension",
    "QualityLevel",
    "RetentionAction",
    "CatalogEntryType",
    "TransformationType",
    "AccessLevel",
    "DataVersion",
    "LineageNode",
    "LineageEdge",
    "QualityRule",
    "QualityResult",
    "QualityReport",
    "RetentionPolicy",
    "RetentionResult",
    "CatalogEntry",
    "TransformationRecord",
    "DataAsset",
    "LifecycleConfig",
    "create_lifecycle_config",
    "create_data_lifecycle_hub",
    "create_quality_rule",
    "create_retention_policy",
    "create_managed_provider",
]
