"""Data Pipeline Module.

Provides data processing capabilities:
- Stream processing with windowing
- Batch job processing
- Data transformations
- ETL pipelines
"""

from src.core.data_pipeline.transform import (
    TransformError,
    Transformer,
    MapTransformer,
    SelectTransformer,
    DropTransformer,
    TypeConvertTransformer,
    ComputeTransformer,
    FilterTransformer,
    ValidateTransformer,
    FlattenTransformer,
    NestTransformer,
    ChainTransformer,
    ConditionalTransformer,
    AggregatorType,
    Aggregator,
    GroupByAggregator,
    WindowSpec,
    WindowFunction,
)
from src.core.data_pipeline.stream import (
    StreamEvent,
    WindowType,
    WindowConfig,
    Window,
    StreamSource,
    StreamSink,
    InMemorySource,
    InMemorySink,
    BufferedSink,
    StreamOperator,
    MapOperator,
    FilterOperator,
    FlatMapOperator,
    TransformerOperator,
    WindowProcessor,
    StreamPipeline,
    ParallelStreamPipeline,
)
from src.core.data_pipeline.batch import (
    JobStatus,
    JobPriority,
    JobConfig,
    JobProgress,
    JobResult,
    BatchJob,
    FunctionJob,
    TransformJob,
    ChainedJob,
    JobScheduler,
    ParallelBatchProcessor,
    ETLPipeline,
)

__all__ = [
    # Transforms
    "TransformError",
    "Transformer",
    "MapTransformer",
    "SelectTransformer",
    "DropTransformer",
    "TypeConvertTransformer",
    "ComputeTransformer",
    "FilterTransformer",
    "ValidateTransformer",
    "FlattenTransformer",
    "NestTransformer",
    "ChainTransformer",
    "ConditionalTransformer",
    "AggregatorType",
    "Aggregator",
    "GroupByAggregator",
    "WindowSpec",
    "WindowFunction",
    # Stream
    "StreamEvent",
    "WindowType",
    "WindowConfig",
    "Window",
    "StreamSource",
    "StreamSink",
    "InMemorySource",
    "InMemorySink",
    "BufferedSink",
    "StreamOperator",
    "MapOperator",
    "FilterOperator",
    "FlatMapOperator",
    "TransformerOperator",
    "WindowProcessor",
    "StreamPipeline",
    "ParallelStreamPipeline",
    # Batch
    "JobStatus",
    "JobPriority",
    "JobConfig",
    "JobProgress",
    "JobResult",
    "BatchJob",
    "FunctionJob",
    "TransformJob",
    "ChainedJob",
    "JobScheduler",
    "ParallelBatchProcessor",
    "ETLPipeline",
]
