#!/usr/bin/env python3
"""Hybrid blind-evaluation quality gate.

Consumes the summary generated by:
`scripts/batch_analyze_dxf_local.py --geometry-only`
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List


DEFAULT_THRESHOLDS: Dict[str, Any] = {
    "min_sample_size": 20,
    "min_weak_label_coverage": 0.70,
    "min_hybrid_accuracy": 0.30,
    "min_gain_vs_graph2d": 0.00,
    "max_hybrid_missing_pred_rate": 0.30,
    "require_geometry_only": True,
    "require_mask_filename": True,
    "require_strip_text": True,
}


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return default


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except Exception:
        return default


def _safe_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return bool(default)
    token = str(value).strip().lower()
    if token in {"1", "true", "yes", "y", "on"}:
        return True
    if token in {"0", "false", "no", "n", "off"}:
        return False
    return bool(default)


def _read_json(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected object JSON: {path}")
    return payload


def _load_yaml_defaults(config_path: str, section: str) -> Dict[str, Any]:
    if not config_path:
        return {}
    path = Path(config_path)
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore
    except Exception:
        return {}
    try:
        payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:
        return {}
    if not isinstance(payload, dict):
        return {}
    section_payload = payload.get(section)
    if not isinstance(section_payload, dict):
        return {}
    return section_payload


def _resolve_thresholds(
    config_payload: Dict[str, Any],
    cli_overrides: Dict[str, Any],
) -> Dict[str, Any]:
    out = dict(DEFAULT_THRESHOLDS)
    for key in DEFAULT_THRESHOLDS.keys():
        if key in config_payload:
            out[key] = config_payload.get(key)
    for key, value in cli_overrides.items():
        if value is not None:
            out[key] = value
    return {
        "min_sample_size": _safe_int(
            out.get("min_sample_size"), DEFAULT_THRESHOLDS["min_sample_size"]
        ),
        "min_weak_label_coverage": _safe_float(
            out.get("min_weak_label_coverage"),
            DEFAULT_THRESHOLDS["min_weak_label_coverage"],
        ),
        "min_hybrid_accuracy": _safe_float(
            out.get("min_hybrid_accuracy"), DEFAULT_THRESHOLDS["min_hybrid_accuracy"]
        ),
        "min_gain_vs_graph2d": _safe_float(
            out.get("min_gain_vs_graph2d"), DEFAULT_THRESHOLDS["min_gain_vs_graph2d"]
        ),
        "max_hybrid_missing_pred_rate": _safe_float(
            out.get("max_hybrid_missing_pred_rate"),
            DEFAULT_THRESHOLDS["max_hybrid_missing_pred_rate"],
        ),
        "require_geometry_only": _safe_bool(
            out.get("require_geometry_only"), DEFAULT_THRESHOLDS["require_geometry_only"]
        ),
        "require_mask_filename": _safe_bool(
            out.get("require_mask_filename"),
            DEFAULT_THRESHOLDS["require_mask_filename"],
        ),
        "require_strip_text": _safe_bool(
            out.get("require_strip_text"), DEFAULT_THRESHOLDS["require_strip_text"]
        ),
    }


def _extract_accuracy_block(summary: Dict[str, Any], key: str) -> Dict[str, Any]:
    weak_labels = summary.get("weak_labels") if isinstance(summary.get("weak_labels"), dict) else {}
    accuracy = weak_labels.get("accuracy") if isinstance(weak_labels.get("accuracy"), dict) else {}
    block = accuracy.get(key)
    return block if isinstance(block, dict) else {}


def evaluate_hybrid_blind_gate(
    summary: Dict[str, Any],
    thresholds: Dict[str, Any],
    *,
    dataset_source: str = "",
    manifest_source: str = "",
    required_manifest_source: str = "",
) -> Dict[str, Any]:
    failures: List[str] = []
    warnings: List[str] = []
    normalized_manifest_source = str(manifest_source or "").strip() or "unknown"
    normalized_required_manifest_source = str(required_manifest_source or "").strip()

    if (
        normalized_required_manifest_source
        and normalized_manifest_source != normalized_required_manifest_source
    ):
        failures.append(
            "manifest_source "
            f"{normalized_manifest_source!r} != required_manifest_source "
            f"{normalized_required_manifest_source!r}"
        )

    geometry_only = _safe_bool(summary.get("geometry_only"), False)
    mask_filename = _safe_bool(summary.get("mask_filename"), False)
    strip_text = _safe_bool(summary.get("strip_text"), False)

    if thresholds["require_geometry_only"] and not geometry_only:
        failures.append("summary.geometry_only must be true.")
    if thresholds["require_mask_filename"] and not mask_filename:
        failures.append("summary.mask_filename must be true.")
    if thresholds["require_strip_text"] and not strip_text:
        failures.append("summary.strip_text must be true.")

    sample_size = _safe_int(summary.get("sample_size"), 0)
    if sample_size < thresholds["min_sample_size"]:
        failures.append(
            f"sample_size {sample_size} < min_sample_size {thresholds['min_sample_size']}"
        )

    weak_labels = summary.get("weak_labels") if isinstance(summary.get("weak_labels"), dict) else {}
    covered_rate = _safe_float(weak_labels.get("covered_rate"), 0.0)
    covered_count = _safe_int(weak_labels.get("covered_count"), 0)
    if covered_rate < thresholds["min_weak_label_coverage"]:
        failures.append(
            f"weak_label_coverage {covered_rate:.4f} < min_weak_label_coverage "
            f"{thresholds['min_weak_label_coverage']:.4f}"
        )

    hybrid_block = _extract_accuracy_block(summary, "hybrid_label")
    graph2d_block = _extract_accuracy_block(summary, "graph2d_label")
    hybrid_accuracy = _safe_float(hybrid_block.get("accuracy"), 0.0)
    graph2d_accuracy = _safe_float(graph2d_block.get("accuracy"), 0.0)
    hybrid_missing_pred_rate = (
        _safe_float(hybrid_block.get("missing_pred"), 0.0)
        / max(1.0, _safe_float(hybrid_block.get("evaluated"), 0.0))
    )
    gain_vs_graph2d = hybrid_accuracy - graph2d_accuracy

    if hybrid_accuracy < thresholds["min_hybrid_accuracy"]:
        failures.append(
            f"hybrid_accuracy {hybrid_accuracy:.4f} < min_hybrid_accuracy "
            f"{thresholds['min_hybrid_accuracy']:.4f}"
        )
    if gain_vs_graph2d < thresholds["min_gain_vs_graph2d"]:
        failures.append(
            f"hybrid_gain_vs_graph2d {gain_vs_graph2d:.4f} < min_gain_vs_graph2d "
            f"{thresholds['min_gain_vs_graph2d']:.4f}"
        )
    if hybrid_missing_pred_rate > thresholds["max_hybrid_missing_pred_rate"]:
        failures.append(
            f"hybrid_missing_pred_rate {hybrid_missing_pred_rate:.4f} > "
            f"max_hybrid_missing_pred_rate {thresholds['max_hybrid_missing_pred_rate']:.4f}"
        )

    if covered_count <= 0:
        warnings.append("weak_labels.covered_count is zero; accuracy signal is unreliable.")

    status = "passed" if not failures else "failed"
    return {
        "status": status,
        "failures": failures,
        "warnings": warnings,
        "input_summary": {
            "dataset_source": str(dataset_source or "").strip() or "unknown",
            "manifest_source": normalized_manifest_source,
            "required_manifest_source": normalized_required_manifest_source,
            "geometry_only": geometry_only,
            "mask_filename": mask_filename,
            "strip_text": strip_text,
        },
        "metrics": {
            "sample_size": sample_size,
            "weak_label_covered_count": covered_count,
            "weak_label_coverage": round(covered_rate, 6),
            "hybrid_accuracy": round(hybrid_accuracy, 6),
            "graph2d_accuracy": round(graph2d_accuracy, 6),
            "hybrid_gain_vs_graph2d": round(gain_vs_graph2d, 6),
            "hybrid_missing_pred_rate": round(hybrid_missing_pred_rate, 6),
            "flags": {
                "geometry_only": geometry_only,
                "mask_filename": mask_filename,
                "strip_text": strip_text,
            },
        },
        "thresholds": thresholds,
    }


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Check Hybrid blind evaluation gate.")
    parser.add_argument("--summary-json", required=True, help="Path to summary JSON.")
    parser.add_argument(
        "--config",
        default="config/hybrid_blind_gate.yaml",
        help="Optional YAML config path.",
    )
    parser.add_argument("--output", default="", help="Optional report output JSON path.")
    parser.add_argument("--min-sample-size", type=int, default=None)
    parser.add_argument("--min-weak-label-coverage", type=float, default=None)
    parser.add_argument("--min-hybrid-accuracy", type=float, default=None)
    parser.add_argument("--min-gain-vs-graph2d", type=float, default=None)
    parser.add_argument("--max-hybrid-missing-pred-rate", type=float, default=None)
    parser.add_argument("--require-geometry-only", type=str, default=None)
    parser.add_argument("--require-mask-filename", type=str, default=None)
    parser.add_argument("--require-strip-text", type=str, default=None)
    parser.add_argument(
        "--dataset-source",
        default="",
        help="Optional dataset source identifier, e.g. configured_dxf_dir or synthetic_manifest.",
    )
    parser.add_argument(
        "--manifest-source",
        default="",
        help="Optional manifest source identifier, e.g. configured or reviewed_benchmark_manifest.",
    )
    parser.add_argument(
        "--require-manifest-source",
        default="",
        help="Fail unless --manifest-source matches this value.",
    )
    args = parser.parse_args(argv)

    summary_path = Path(args.summary_json)
    if not summary_path.exists():
        raise SystemExit(f"summary not found: {summary_path}")

    config_payload = _load_yaml_defaults(args.config, "hybrid_blind_gate")
    thresholds = _resolve_thresholds(
        config_payload=config_payload,
        cli_overrides={
            "min_sample_size": args.min_sample_size,
            "min_weak_label_coverage": args.min_weak_label_coverage,
            "min_hybrid_accuracy": args.min_hybrid_accuracy,
            "min_gain_vs_graph2d": args.min_gain_vs_graph2d,
            "max_hybrid_missing_pred_rate": args.max_hybrid_missing_pred_rate,
            "require_geometry_only": args.require_geometry_only,
            "require_mask_filename": args.require_mask_filename,
            "require_strip_text": args.require_strip_text,
        },
    )
    summary = _read_json(summary_path)
    report = evaluate_hybrid_blind_gate(
        summary=summary,
        thresholds=thresholds,
        dataset_source=str(args.dataset_source or ""),
        manifest_source=str(args.manifest_source or ""),
        required_manifest_source=str(args.require_manifest_source or ""),
    )
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report.get("status") == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
