#!/usr/bin/env python3
"""Generate a brep_golden_manifest.v1 skeleton by scanning a directory tree.

Hand-writing 50–100 cases × ~14 fields is error-prone (~700–1400 fields).
This scaffolder walks a root, emits one structurally-valid case per
STEP/IGES file, infers what it safely can (id / path / format /
source_type / release_eligible / expected_behavior), and leaves the
human-judgement fields as explicit TODO placeholders so the validator
and the human reviewer can both see exactly what still needs filling.

`source_type` is inferred from the first path segment under `root`
(convention: `internal/`, `public_nc/`, `vendor/`, …). Anything not
matching a known bucket defaults to `internal` and is tagged
`TODO-source-type` so it cannot silently slip into the release floor
mis-classified.

Topology probing is intentionally NOT done here (it needs OpenCASCADE,
which is CI-only). `expected_topology` is emitted as a conservative
placeholder tagged `TODO-topology`; the OCC-provisioned
`brep-golden-eval.yml` run is where real minima get tightened.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

# Kept in sync with scripts/validate_brep_golden_manifest.py.
SCHEMA_VERSION = "brep_golden_manifest.v1"
ALLOWED_FORMATS = {"step", "stp", "iges", "igs"}
KNOWN_SOURCE_BUCKETS = {
    "internal": "internal",
    "real_world": "real_world",
    "vendor": "vendor",
    "public_cad": "public_cad",
    "public_nc": "public_nc",
    "fixture": "fixture",
    "synthetic_demo": "synthetic_demo",
    "generated_mock": "generated_mock",
}
RELEASE_EXCLUDED_SOURCE_TYPES = {
    "fixture",
    "synthetic_demo",
    "generated_mock",
    "public_nc",
}
_ID_SAFE = re.compile(r"[^a-zA-Z0-9_]+")


def _slug(text: str) -> str:
    return _ID_SAFE.sub("_", text).strip("_").lower() or "case"


def _iter_brep_files(root: Path) -> List[Path]:
    files: List[Path] = []
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix.lower().lstrip(".") in ALLOWED_FORMATS:
            files.append(path)
    return files


def _infer_source_type(rel_parts: Sequence[str]) -> tuple[str, bool]:
    """Return (source_type, inferred_cleanly).

    ONLY the first path segment under ``root`` is authoritative — this
    matches the DESIGN §2.2 contract ("source_type inferred from first
    path segment"). Deeper segments are deliberately ignored: a nested
    layout like ``mystery/public_nc/x.step`` must NOT be silently
    classified as ``public_nc`` just because a known bucket name appears
    further down. Such a file defaults to ``internal`` AND is reported
    as not-cleanly-inferred so the caller tags it ``TODO-source-type``.
    This prevents silent mis-classification in either direction —
    pulling a non-release file into the release floor, or dropping a
    release-eligible file out of it — which a deep-scan would allow.
    """
    if rel_parts:
        bucket = KNOWN_SOURCE_BUCKETS.get(rel_parts[0].strip().lower())
        if bucket:
            return bucket, True
    return "internal", False


def build_skeleton(
    root: Path,
    *,
    manifest_root: Optional[str] = None,
    name: str = "B-Rep STEP/IGES Golden Manifest",
    description: str = "Skeleton generated by build_brep_golden_manifest_skeleton.py — fill TODO fields.",
) -> Dict[str, Any]:
    root = Path(root)
    files = _iter_brep_files(root)
    cases: List[Dict[str, Any]] = []
    seen_ids: Dict[str, int] = {}
    for path in files:
        rel = path.relative_to(root)
        rel_parts = rel.parts[:-1]
        source_type, clean = _infer_source_type(rel_parts)
        base_id = _slug(rel.as_posix().rsplit(".", 1)[0])
        if base_id in seen_ids:
            seen_ids[base_id] += 1
            case_id = f"{base_id}_{seen_ids[base_id]}"
        else:
            seen_ids[base_id] = 0
            case_id = base_id
        fmt = path.suffix.lower().lstrip(".")
        release_eligible = source_type not in RELEASE_EXCLUDED_SOURCE_TYPES
        tags = ["TODO-part-family", "TODO-license", "TODO-topology"]
        if not clean:
            tags.append("TODO-source-type")
        cases.append(
            {
                "id": case_id,
                "path": rel.as_posix(),
                "format": fmt,
                "source_type": source_type,
                "release_eligible": release_eligible,
                "part_family": "TODO",
                "license": "TODO",
                "expected_behavior": "parse_success",
                "expected_topology": {
                    "faces_min": 1,
                    "edges_min": 0,
                    "solids_min": 0,
                    "graph_nodes_min": 1,
                    "surface_types": [],
                },
                "tags": tags,
            }
        )
    return {
        "schema_version": SCHEMA_VERSION,
        "name": name,
        "description": description,
        "root": manifest_root if manifest_root is not None else str(root),
        "cases": cases,
    }


def summarize(manifest: Dict[str, Any]) -> Dict[str, Any]:
    cases = manifest.get("cases", [])
    by_source: Dict[str, int] = {}
    todo_source = 0
    release_eligible = 0
    for case in cases:
        st = case.get("source_type", "?")
        by_source[st] = by_source.get(st, 0) + 1
        if "TODO-source-type" in (case.get("tags") or []):
            todo_source += 1
        if case.get("release_eligible"):
            release_eligible += 1
    return {
        "case_count": len(cases),
        "release_eligible_count": release_eligible,
        "source_type_counts": by_source,
        "needs_source_type_review": todo_source,
        "all_need_part_family_license_topology": len(cases),
    }


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, help="Directory tree to scan.")
    parser.add_argument(
        "--manifest-root",
        default="",
        help="Value to write into manifest `root` (default: --root literal).",
    )
    parser.add_argument("--name", default="B-Rep STEP/IGES Golden Manifest")
    parser.add_argument("--output-json", default="", help="Write skeleton here (default: stdout).")
    args = parser.parse_args(argv)

    root = Path(args.root).expanduser()
    if not root.is_dir():
        print(f"error: --root is not a directory: {root}", file=sys.stderr)
        return 2

    manifest = build_skeleton(
        root,
        manifest_root=args.manifest_root or None,
        name=args.name,
    )
    rendered = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    if args.output_json:
        out = Path(args.output_json).expanduser()
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(rendered, encoding="utf-8")
        print(f"skeleton_written={out}", file=sys.stderr)
    else:
        sys.stdout.write(rendered)

    summary = summarize(manifest)
    print(json.dumps(summary, ensure_ascii=False, indent=2), file=sys.stderr)
    if summary["case_count"] == 0:
        print(
            f"warning: no STEP/IGES files found under {root}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
