#!/usr/bin/env python3
"""Run Graph2D training recipes across multiple seeds and aggregate metrics."""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional


RECIPE_OVERRIDES: Dict[str, Dict[str, Any]] = {
    "baseline": {},
    "focal_balanced": {
        "loss": "focal",
        "class-weighting": "sqrt",
        "sampler": "balanced",
    },
    "logit_balanced": {
        "loss": "logit_adjusted",
        "class-weighting": "sqrt",
        "sampler": "balanced",
    },
    "geom_heavy": {
        "dxf-max-nodes": 300,
        "dxf-sampling-strategy": "importance",
    },
}


def _parse_seeds(raw: str) -> List[int]:
    seeds: List[int] = []
    for token in str(raw or "").split(","):
        item = token.strip()
        if not item:
            continue
        try:
            seeds.append(int(item))
        except ValueError as exc:
            raise ValueError(f"invalid seed: {item}") from exc
    return seeds


def _parse_recipes(raw: str) -> List[str]:
    return [token.strip() for token in str(raw or "").split(",") if token.strip()]


def _build_train_command(
    *,
    python_exe: str,
    train_script: str,
    base_args: List[str],
    recipe_name: str,
    seed: int,
    checkpoint_path: Path,
    metrics_path: Path,
) -> List[str]:
    cmd = [python_exe, train_script, *base_args]
    cmd.extend(["--seed", str(int(seed))])
    cmd.extend(["--output", str(checkpoint_path)])
    cmd.extend(["--metrics-out", str(metrics_path)])
    overrides = RECIPE_OVERRIDES.get(recipe_name)
    if overrides is None:
        raise ValueError(f"unknown recipe: {recipe_name}")
    for key, value in overrides.items():
        if isinstance(value, bool):
            if value:
                cmd.append(f"--{key}")
            continue
        cmd.extend([f"--{key}", str(value)])
    return cmd


def _read_metrics(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return float(default)


def _build_summary(rows: Iterable[Dict[str, Any]]) -> Dict[str, Any]:
    rows_list = list(rows)
    if not rows_list:
        return {
            "total_runs": 0,
            "executed_runs": 0,
            "failed_runs": 0,
            "best_recipe": "",
            "best_seed": None,
            "best_val_acc": 0.0,
        }
    best_row = max(rows_list, key=lambda r: _safe_float(r.get("best_val_acc"), 0.0))
    executed = [r for r in rows_list if str(r.get("return_code", "")).strip() != ""]
    failed = [r for r in executed if int(r.get("return_code", 0)) != 0]
    return {
        "total_runs": len(rows_list),
        "executed_runs": len(executed),
        "failed_runs": len(failed),
        "best_recipe": str(best_row.get("recipe") or ""),
        "best_seed": int(best_row.get("seed", 0)) if best_row.get("seed") is not None else None,
        "best_val_acc": _safe_float(best_row.get("best_val_acc"), 0.0),
    }


def _recipe_cli_args(recipe_name: str) -> List[str]:
    overrides = RECIPE_OVERRIDES.get(recipe_name) or {}
    args: List[str] = []
    for key, value in overrides.items():
        if isinstance(value, bool):
            if value:
                args.append(f"--{key}")
            continue
        args.extend([f"--{key}", str(value)])
    return args


def _write_recommended_env(
    *,
    path: Path,
    best_row: Dict[str, Any],
) -> None:
    recipe = str(best_row.get("recipe") or "").strip()
    seed = int(best_row.get("seed", 0) or 0)
    best_val_acc = _safe_float(best_row.get("best_val_acc"), 0.0)
    args = _recipe_cli_args(recipe)
    args_text = " ".join(args)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "# Auto-generated by scripts/sweep_graph2d_train_recipes.py",
                f"GRAPH2D_SWEEP_BEST_RECIPE={recipe}",
                f"GRAPH2D_SWEEP_BEST_SEED={seed}",
                f"GRAPH2D_SWEEP_BEST_VAL_ACC={best_val_acc:.6f}",
                f"GRAPH2D_SWEEP_BEST_ARGS={args_text}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_best_run_script(
    *,
    path: Path,
    best_row: Dict[str, Any],
    train_script: str,
    base_args: List[str],
) -> None:
    recipe = str(best_row.get("recipe") or "").strip()
    seed = int(best_row.get("seed", 0) or 0)
    recipe_args = _recipe_cli_args(recipe)
    quoted_base_args = " ".join(f'"{arg}"' for arg in base_args)
    quoted_recipe_args = " ".join(f'"{arg}"' for arg in recipe_args)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "",
                "# Run from repository root, or set TRAIN_SCRIPT to an absolute path.",
                f'TRAIN_SCRIPT="${{TRAIN_SCRIPT:-{train_script}}}"',
                'PYTHON_BIN="${PYTHON_BIN:-python3}"',
                'RUN_ROOT="${RUN_ROOT:-$(pwd)/tmp/graph2d_best_recipe_run_$(date +%Y%m%d_%H%M%S)}"',
                'mkdir -p "$RUN_ROOT"',
                "",
                f"BASE_ARGS=({quoted_base_args})",
                f"RECIPE_ARGS=({quoted_recipe_args})",
                "",
                'CMD=(',
                '  "$PYTHON_BIN" "$TRAIN_SCRIPT"',
                '  "${BASE_ARGS[@]}"',
                f'  --seed "{seed}"',
                '  --output "$RUN_ROOT/model.pth"',
                '  --metrics-out "$RUN_ROOT/metrics.json"',
                '  "${RECIPE_ARGS[@]}"',
                ')',
                'echo "Running best recipe command:"',
                'printf " %q" "${CMD[@]}"',
                'echo ""',
                '"${CMD[@]}"',
                'echo "Done. artifacts: $RUN_ROOT"',
                "",
            ]
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)


def _write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    keys: set[str] = set()
    for row in rows:
        keys.update(str(k) for k in row.keys())
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=sorted(keys))
        writer.writeheader()
        writer.writerows(rows)


def _run_command(command: List[str], *, cwd: Path) -> int:
    proc = subprocess.run(command, cwd=str(cwd), check=False)
    return int(proc.returncode)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sweep Graph2D train recipes across seeds and aggregate metrics.",
    )
    parser.add_argument("--recipes", default="baseline,focal_balanced")
    parser.add_argument("--seeds", default="7,21,42")
    parser.add_argument("--train-script", default="scripts/train_2d_graph.py")
    parser.add_argument(
        "--base-args-json",
        default="[]",
        help="JSON array of extra args passed to train script.",
    )
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--fail-on-error", action="store_true")
    parser.add_argument("--max-runs", type=int, default=0)
    parser.add_argument(
        "--work-root",
        default="",
        help="Output root for sweep artifacts (default: /tmp/graph2d_train_recipe_sweep_<ts>).",
    )
    parser.add_argument(
        "--recommended-env-out",
        default="",
        help=(
            "Optional output path for best-recipe env snippet "
            "(default: <work-root>/recommended_graph2d_train.env)."
        ),
    )
    parser.add_argument(
        "--best-run-script-out",
        default="",
        help=(
            "Optional output path for executable script that reruns the best recipe "
            "(default: <work-root>/run_best_recipe.sh)."
        ),
    )
    args = parser.parse_args(argv)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    work_root = (
        Path(args.work_root)
        if str(args.work_root).strip()
        else Path("/tmp") / f"graph2d_train_recipe_sweep_{stamp}"
    )
    work_root.mkdir(parents=True, exist_ok=True)

    try:
        base_args_raw = json.loads(str(args.base_args_json))
        if not isinstance(base_args_raw, list):
            raise ValueError("base-args-json must be a JSON array")
        base_args = [str(item) for item in base_args_raw]
    except Exception as exc:
        print(f"Invalid --base-args-json: {exc}")
        return 2

    try:
        recipes = _parse_recipes(str(args.recipes))
        seeds = _parse_seeds(str(args.seeds))
    except ValueError as exc:
        print(f"Invalid sweep arguments: {exc}")
        return 2
    if not recipes:
        print("No recipes provided.")
        return 2
    if not seeds:
        print("No seeds provided.")
        return 2

    train_script = str(args.train_script)
    runs: List[Dict[str, Any]] = []
    for recipe in recipes:
        if recipe not in RECIPE_OVERRIDES:
            print(f"Unknown recipe: {recipe}")
            return 2
        for seed in seeds:
            runs.append({"recipe": recipe, "seed": int(seed)})
    if int(args.max_runs) > 0:
        runs = runs[: int(args.max_runs)]

    output_rows: List[Dict[str, Any]] = []
    for run in runs:
        recipe = str(run["recipe"])
        seed = int(run["seed"])
        run_dir = work_root / f"{recipe}__seed_{seed}"
        run_dir.mkdir(parents=True, exist_ok=True)
        checkpoint_path = run_dir / "model.pth"
        metrics_path = run_dir / "metrics.json"
        command = _build_train_command(
            python_exe=str(args.python),
            train_script=train_script,
            base_args=base_args,
            recipe_name=recipe,
            seed=seed,
            checkpoint_path=checkpoint_path,
            metrics_path=metrics_path,
        )

        return_code: Optional[int] = None
        if bool(args.execute):
            return_code = _run_command(command, cwd=Path.cwd())

        metrics = _read_metrics(metrics_path)
        output_rows.append(
            {
                "recipe": recipe,
                "seed": seed,
                "return_code": return_code if return_code is not None else "",
                "command": " ".join(command),
                "checkpoint_path": str(checkpoint_path),
                "metrics_path": str(metrics_path),
                "best_val_acc": _safe_float(metrics.get("best_val_acc"), 0.0),
                "final_val_acc": _safe_float(metrics.get("final_val_acc"), 0.0),
                "best_epoch": int(metrics.get("best_epoch", 0) or 0),
                "epochs_ran": int(metrics.get("epochs_ran", 0) or 0),
            }
        )

    results_csv = work_root / "train_recipe_sweep_results.csv"
    results_json = work_root / "train_recipe_sweep_results.json"
    summary_json = work_root / "train_recipe_sweep_summary.json"

    _write_csv(results_csv, output_rows)
    results_json.write_text(
        json.dumps(output_rows, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    summary = _build_summary(output_rows)
    recommended_env_path = (
        Path(args.recommended_env_out)
        if str(args.recommended_env_out).strip()
        else work_root / "recommended_graph2d_train.env"
    )
    best_run_script_path = (
        Path(args.best_run_script_out)
        if str(args.best_run_script_out).strip()
        else work_root / "run_best_recipe.sh"
    )
    if output_rows:
        best_row = max(output_rows, key=lambda r: _safe_float(r.get("best_val_acc"), 0.0))
        _write_recommended_env(path=recommended_env_path, best_row=best_row)
        _write_best_run_script(
            path=best_run_script_path,
            best_row=best_row,
            train_script=train_script,
            base_args=base_args,
        )
        summary["recommended_env_file"] = str(recommended_env_path)
        summary["best_run_script"] = str(best_run_script_path)
        summary["best_args"] = _recipe_cli_args(str(summary.get("best_recipe") or ""))
    else:
        summary["recommended_env_file"] = ""
        summary["best_run_script"] = ""
        summary["best_args"] = []
    summary_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote results: {results_csv}")
    print(f"Wrote summary: {summary_json}")
    if summary.get("recommended_env_file"):
        print(f"Wrote recommended env: {summary.get('recommended_env_file')}")
    if summary.get("best_run_script"):
        print(f"Wrote best run script: {summary.get('best_run_script')}")

    if bool(args.execute) and bool(args.fail_on_error):
        failed = [row for row in output_rows if int(row.get("return_code", 0) or 0) != 0]
        if failed:
            print(f"Sweep failed: {len(failed)} runs returned non-zero exit codes.")
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
